### ISSUE TITLE
Add SQL Type to dbColumnInfo

### ISSUE THREAD

**Issue by ankane** [r-dbi/RMariaDB#100]
Hi, it looks like `dbColumnInfo` currently only returns the R type. It'd be great to return the SQL type as well (as RMySQL does).

**Comment by krlmlr** [comment]
Related: https://github.com/r-dbi/RSQLite/issues/263

**Comment by krlmlr** [comment]
The relevant code is in https://github.com/r-dbi/RMySQL/blob/main/src/fields.c, we may want to query in `MariaResultPrep::cache_metadata()` .

**Comment by ankane** [comment]
Cleaning up stale issues
