### ISSUE TITLE
Error while installing on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by nishit26** [r-dbi/RMariaDB#101]
While installing RMariaDB on Ubuntu 18.0.4 getting below error:

g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RMariaDB.so DbConnection.o DbResult.o MariaBinding.o MariaResultImpl.o MariaResultPrep.o MariaResultSimple.o MariaRow.o MariaTypes.o MariaUtils.o RcppExports.o connection.o driver.o result.o -L/usr/lib/x86_64-linux-gnu/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto -L/usr/lib/R/lib -lR
**/usr/bin/x86_64-linux-gnu-ld: cannot find -lssl
/usr/bin/x86_64-linux-gnu-ld: cannot find -lcrypto**
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'RMariaDB.so' failed
make: *** [RMariaDB.so] Error 1
ERROR: compilation failed for package ‘RMariaDB’
* removing ‘/usr/local/lib/R/site-library/RMariaDB’

**Comment by krlmlr** [comment]
Thanks. I ran on my system (Ubuntu 18.04):

```sh
$ apt-file search libssl.a
libssl-dev: /usr/lib/x86_64-linux-gnu/libssl.a
libssl1.0-dev: /usr/lib/x86_64-linux-gnu/libssl.a
$ apt-file search libcrypto.a
libssl-dev: /usr/lib/x86_64-linux-gnu/libcrypto.a
libssl1.0-dev: /usr/lib/x86_64-linux-gnu/libcrypto.a
```

This means that installing `libssl-dev` should fix the problems.

@jeroen: Do you think `libmariadb-dev` should depend on `libssl-dev` ? Anyway, it seems worth adding to the anticonf message.

**Comment by jeroen** [comment]
I don't think that's the problem here.@nishit26  can you show us the complete installation output? In particular the first few lines where it says how it obtained the linker flags? Because on my Ubuntu 18.04 server it does not use openssl at all:

```
* installing *source* package ‘RMariaDB’ ...
** package ‘RMariaDB’ successfully unpacked and MD5 sums checked
Using mysql_config
Found mysql_config/mariadb_config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/mysql
Using PKG_LIBS=-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -ldl

...

g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RMariaDB.so DbConnection.o DbResult.o MariaBinding.o MariaResultImpl.o MariaResultPrep.o MariaResultSimple.o MariaRow.o MariaTypes.o MariaUtils.o RcppExports.o connection.o driver.o result.o -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -ldl -L/usr/lib/R/lib -lR
installing to /home/jeroen/R/x86_64-pc-linux-gnu-library/3.5/RMariaDB/libs
```

**Comment by manikant-prasad** [comment]
I was facing this problem on Ubuntu 18.04 server and below is the first few lines of output where it obtains the flags. The output is little different from what @jeroen has got. And installing `libssl-dev` worked for me. 

```
* installing *source* package ‘plogr’ ...
** package ‘plogr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (plogr)
* installing *source* package ‘RMariaDB’ ...
** package ‘RMariaDB’ successfully unpacked and MD5 sums checked
Using mariadb_config
WARNING: Connector versions prior to 2.3.4/3.0.3 have a known problem with retrieving string and blob data. See https://github.com/r-dbi/RMariaDB/issues/53 for d
Found mysql_config/mariadb_config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/mariadb -I/usr/include/mariadb/mysql
Using PKG_LIBS=-L/usr/lib/x86_64-linux-gnu/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto
** libs
```

**Comment by krlmlr** [comment]
I see that `mariadb_config` output is different. SSL might be available, but are the `-dev` libraries always installed by default?

**Comment by Irene-GM** [comment]
I was having the same problem and installing libssl-dev (`sudo apt-get install -y libssl-dev`) worked for me. Thanks for the hint.
