### ISSUE TITLE
Bad Handshake when connecting to 

### ISSUE THREAD

**Issue by stevebuckleysparx** [r-dbi/RMariaDB#103]
When connecting to a remote MySQL database using RMariaDB I get Bad Handshakes when using both Mac and Linux.

I'm calling 

    con <- dbConnect(RMariaDB::MariaDB(), 
        user = 'user', host = 'host', password = 'password',
        client.flag = RMariaDB::CLIENT_SSL)

The database requires SSL and without the client.flag I get an Access Denied error. Connecting to the database from the command line with the flag --ssl-mode=REQUIRED is totally fine. I'm really struggling to understand what the issue is.

**Comment by krlmlr** [comment]
Thanks. I have no idea what could be wrong here. I guess you already tried running `R` from the same command line as the _RMariaDB_ CLI?

One way to troubleshoot would be to run both `R` and `mysql` with `strace` to understand which files are accessed.

**Comment by krlmlr** [comment]
Closing, stale.
