### ISSUE TITLE
Slow writing data to MySQL database hosted on Google Cloud

### ISSUE THREAD

**Issue by ben519** [r-dbi/RMariaDB#104]
I recently created a database using Google Cloud MySQL (2nd generation) and have been running into some performance issues trying to write data to the database via RMariaDB.  Observe the following...

```
# Connect to database using MariaDB driver (slow)
mycon <- DBI::dbConnect(
  drv = RMariaDB::MariaDB(),
  dbname = "mydb", 
  host = "11.111.111.111", 
  user = "foo",
  password = ""
)

# Write table 'iris'
system.time(RMariaDB::dbWriteTable(conn = mycon, name = "iris", value = iris, row.names = FALSE, overwrite = TRUE))
# 9.515 seconds

RMariaDB::dbDisconnect(mycon)

# Connect to database using MySQL driver (fast)
mycon <- DBI::dbConnect(
  drv = DBI::dbDriver("MySQL"),
  dbname = "mydb", 
  host = "11.111.111.111", 
  user = "foo",
  password = ""
)

# Write table 'iris'
system.time(RMariaDB::dbWriteTable(conn = mycon, name = "iris", value = iris, row.names = FALSE, overwrite = TRUE))
# 0.441 seconds

# Attempt 1 to append data to table
system.time(RMariaDB::dbAppendTable(conn = mycon, name = "iris", value = iris))
# Error in .local(conn, statement, ...) : 
#   unused argument (param = unname(as.list(value)))
# Timing stopped at: 0.005 0 0.005

# Attemp 2 to append data to table, using RMySQL
system.time(RMySQL::dbWriteTable(conn = mycon, name = "iris", value = iris, row.names = FALSE, overwrite = FALSE, append = TRUE))
# 0.206 seconds

```

My questions are

1. *Should* it be possible to write data to a MySQL database on Google Cloud in a reasonable amount of time?  (Perhaps I am trying to do something that was not intended to be done.)
2. As shown by the error above, I cannot append data to a table using RMariaDB with a MySQL driver.  Is this a bug? 

For now I am stuck using RMySQL :/

Thanks, I **really** appreciate all the hard work done on this package!

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5
RMariaDB_1.0.6
```

**Comment by m-saenger** [comment]
I ran a script with a `DBI::dbWrite` statement for different number of records `n.records`. Once from my local machine (macOS) and once from the Ubuntu 16.04 server hosted at Digitalocean. Target was a MySQL database (InnoDB engine) hosted at Digitalocean. 

Using a RMariaDB() connection results in a much slower writing speed  for `n.records` > 10^3 on Ubuntu. On macOS performance of RMariaDB() is poor even for low `n.records`. 

**Results Mac macOS**
```
n.records time.maria time.mysql
1: 1e+00      0.669      0.216
2: 1e+01      0.647      0.242
3: 1e+02      2.680      0.238
4: 1e+03     23.017      0.413
5: 1e+04    236.299      0.507
6: 1e+05   2196.433      2.191
```

**Results Ubuntu 16.04:**
```
n.records time.maria time.mysql
1: 1e+00      0.130      0.038
2: 1e+01      0.119      0.110
3: 1e+02      0.204      0.039
4: 1e+03      0.124      0.119
5: 1e+04      0.832      0.189
6: 1e+05      7.183      0.996
7: 1e+06     71.885      9.135
8: 1e+07    724.093    122.916
```
Let me know if you need further information.

Best, Matt

**Script (not a reprex):**
```
library(DBI)
library(RMariaDB)
library(RMySQL)
library(data.table)

n.records <- 10^(0:5)
tbl <- "test"
rmysql.settingsfile <- path.expand("~/.my.cnf")

l <- lapply(n.records, function(n){
  df <- data.frame(x = 1:n, y = rep("a", n), z = seq(Sys.time(), Sys.time() - 3600, length.out = n))
  
  time.maria <- system.time({
    conn <- dbConnect(RMariaDB::MariaDB(), default.file = rmysql.settingsfile, group = "dbadmin")
    dbWriteTable(conn, tbl, df, overwrite = T, row.names = F)
    dbDisconnect(conn)
  })
  print(time.maria)
  time.mysql <- system.time({
    conn <- dbConnect(RMySQL::MySQL(), default.file = rmysql.settingsfile, group = "dbadmin")
    dbWriteTable(conn, tbl, df, overwrite = T, row.names = F)
    dbDisconnect(conn)
  })
  print(time.mysql)
  data.table(n, time.maria = time.maria[3], time.mysql = time.mysql[3])
})
dt <- rbindlist(l)
print(dt)
```


**macOS (local):**
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6
RMariaDB_1.0.6
DBI_1.0.0

mariadbClientLibraryVersions()
10.2.9 10.2.9 
100209 100209 
```

**Ubuntu**
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS
RMariaDB_1.0.6
RMySQL_0.10.15
DBI_1.0.0

mariadbClientLibraryVersions()
5.7.23 5.7.23 
 50723  50723 
```

**Comment by krlmlr** [comment]
Thanks. `dbAppendTable()` should be fixed now in the dev version of _DBI_. In your tests, OS X seems to run with MariaDB libraries, Ubuntu with MySQL. Can you confirm? How do the results look like with `dbAppendTable()` ?

**Comment by ben519** [comment]
@krlmlr thanks for the response. The timings in my post are still accurate.  Do you have any suggestions on how I can debug this issue or make it easier for you to help me diagnose the problem?

**Comment by m-saenger** [comment]
Timings from my previous post are still valid, too. I used the dev version:

Package: DBI
Version: 1.0.0.9000

`dbWriteTable` and `dbAppendTable` produce similar results

> OS X seems to run with MariaDB libraries, Ubuntu with MySQL.

I don't quite understand what you mean with that. Is it what `mariadbClientLibraryVersions()` shows? I ran the exact same script both on OS X and Ubuntu. 

Happy to help you further.

Best, Matt

**Comment by krlmlr** [comment]
It's about the database connector -- MySQL and MariaDB have different system libraries ("Connector-C"), both of which can be used with _RMariaDB_. Maybe this explains the difference?

I'll try replicating this on my machine with both libraries.

**Comment by krlmlr** [comment]
Do the timing differences also occur with a local or on-premises database?

**Comment by ben519** [comment]
The timing differences don't occur for me using a local database (although I have mariadb installed on my laptop, not mysql).

**Comment by krlmlr** [comment]
Thanks. Is the local CPU busy when the queries are run against GCE?

**Comment by ben519** [comment]
No noticeable increase in CPU load while the queries are running against GCE.

**Comment by rspreafico-vir** [comment]
Confirming huge performance difference between RMySQL and RMariaDB

**Comment by mabe0033** [comment]
I have seen huge performance differences, too.

AFAICS, **for writing a data.frame,** RMySQL writes a temporary file and uses the SQL statement "LOAD DATA LOCAL INFILE" (which is recommended for performance reasons) whereas RMariaDB (after splitting the 'write' task into a 'create' and 'append' task) constructs an "INSERT" statement in the 'append' subtask (while defaulting to sqlAppendTableTemplate in DBI).

Maybe, the behaviour of RMySQL should be adopted in this situation (writing or appending a data.frame).

**Comment by kforner** [comment]
Hi,

> krlmlr added this to the 1.1.0 milestone 5 days ago

Any (even rough) idea about when this may be fixed ? 
I'm asking this respectfully because we are badly impacted by this problem. 
We can no longer use RMySQL because of another issue (disconnection/freeze for medium/large uploads) and SSL support.

It would be really helpful to know if a solution may happen soon, or if we have to implement some contingency plans.

Thanks a lot for all this work!

**Comment by kforner** [comment]
Just for sharing, I'm currently using this function as a work-around for use with RMariaDB 1.0.10:
```
#' fast replacement for RMariaDB::dbWriteTable
#' 
#' @inheritParams DBI::dbWriteTable
#' @param field.types 	Optional, overrides default choices of field types, 
#' 											derived from the classes of the columns in the data frame.
#' @param append				a logical specifying whether to append to an existing table in the DBMS. If appending, 
#' 											then the table (or temporary table) must exist, otherwise an error is reported.
#' 											Its default is FALSE.
#' @param ... passed to DBI::dbWriteTable
#' @return TRUE on success
#' @export
mysql_fast_db_write_table <- function(conn, name, value, field.types = NULL,  append = FALSE, ...) {
  
  if (!append) {
    # fix for the field types
    if (is.null(field.types)) {
      field.types <- vapply(value, DBI::dbDataType, dbObj = conn, FUN.VALUE = character(1))
    }
    DBI::dbWriteTable(conn, name, value[NULL,], field.types = field.types, ...)
  }
  
  ### write a temp csv file
  fn <- normalizePath(tempfile("rsdbi"), winslash = "/",  mustWork = FALSE)
  safe.write(value, file = fn)
  on.exit(unlink(fn), add = TRUE)
  
  DBI::dbWriteTable(conn, name, fn, append = TRUE, overwrite = FALSE, header = FALSE, sep = '\t')
}

# copied from RMySQL:::safe.write
safe.write <- function (value, file, batch, ...) 
{
  N <- nrow(value)
  if (N < 1) {
    warning("no rows in data.frame")
    return(NULL)
  }
  digits <- options(digits = 17)
  on.exit(options(digits))
  if (missing(batch) || is.null(batch)) 
    batch <- 10000
  else if (batch <= 0) 
    batch <- N
  from <- 1
  to <- min(batch, N)
  conb <- file(file, open = "wb")
  while (from <= N) {
    utils::write.table(escape(value[from:to, , drop = FALSE]), file = conb, 
        append = TRUE, quote = FALSE, sep = "\t", na = "\\N", 
        row.names = FALSE, col.names = FALSE, eol = "\n", 
        ...)
    from <- to + 1
    to <- min(to + batch, N)
  }
  close(conb)
  invisible(NULL)
}

# copied from RMySQL:::escape
escape <- function (table) 
{
  table <- as.data.frame(table)
  repcols <- which(sapply(table, is.character) | sapply(table, 
          is.factor))
  for (rc in repcols) {
    table[, rc] <- gsub("\\\\", "\\\\\\\\", table[, rc])
    table[, rc] <- gsub("\\n", "\\\\n", table[, rc])
    table[, rc] <- gsub("\\t", "\\\\t", table[, rc])
  }
  table
}
```

**Comment by kforner** [comment]
cf my post on https://github.com/r-dbi/RMariaDB/issues/162

**Comment by krlmlr** [comment]
I'm making this a priority, can't give a concrete timeline though.

**Comment by krlmlr** [comment]
Planning to release an update that uses `LOAD DATA LOCAL INFILE` very soon. Closing this issue in favor of #11.
