### ISSUE TITLE
Can't select all records in MySQL Database

### ISSUE THREAD

**Issue by gregforcey** [r-dbi/RMariaDB#108]
I'm trying to select all records from a remote MySQL database with 171,439 observations. I'm getting some odd behavior when using `RMariaDB` to select the records. If I use the same code but use `RMySQL` it works fine.  Here is the setup:
```r
project_db <- RMariaDB::dbConnect(RMariaDB::MariaDB(), group="group")
all.query <- RMariaDB::dbSendQuery(project_db, "select * from table")
```
The following code causes R to crash:
```r
query<- RMariaDB::dbFetch(all.query, n=-1)
```
If I use the following I get a data frame with 100,000 observations (expected behavior)
```r
query<- RMariaDB::dbFetch(all.query, n=100000)
```
If I use the following I get a data frame with 71,439 observations (not what it should be)
```r
query<- RMariaDB::dbFetch(all.query, n=200000)
```

**Comment by sbohora** [comment]
@gregforcey: When I replace the parameter `group` with `dbname`, it works for me.

```r
con <- RMariaDB::dbConnect(
  RMariaDB::MariaDB(), 
  user='user', 
  password='password', 
  dbname='group'
  )
```

**Comment by krlmlr** [comment]
Thanks. How many columns of what type does this table have? Would you be able to share a dump?

**Comment by gregforcey** [comment]
The latest version of the table has 232,922 rows with 25 columns consisting of a variety of character, integer, time and double columns. I just tried the query again with the `n=-1` argument and a data frame was created with all the observations, but the console showed the following warning message
```
Warning message:
In connection_release(conn@ptr) : There is a result object still in use.
The connection will be automatically released when it is closed
```
This was with a restated R session so I'm not sure why anything would be in use.

**Comment by krlmlr** [comment]
To avoid the warning, you need to call `dbClearResult()` after `dbFetch()`, or call `dbGetQuery()` instead (which is send + fetch + clear).

Please let me know if this problem occurs again. I'll try later with `nycflights13::flights` copied to the database, this has similar structure and size.

**Comment by gregforcey** [comment]
It's now working as expected with all the observations with the `n=-1` argument. I can't explain why it wasn't extracting all the observations before. 

Also `dbClearResult()` works as described to suppress the warning. Thanks.

**Comment by krlmlr** [comment]
Did you update the _RMariaDB_ package in the meantime by any chance?

**Comment by gregforcey** [comment]
If there was a new version released on CRAN since my original post, then yes I updated. I normally keep all my packages updated. That would explain the error going away.

**Comment by krlmlr** [comment]
Thanks!

**Comment by krlmlr** [comment]
Closing for now, please open a new issue if problems persist.
