### ISSUE TITLE
"select 1" returns integer64

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/RMariaDB#112]
I'm not sure if it is a desired behavior that a simple `select 1` query returns a data frame of an `integer64` column of `1`.

```r
> str(dbGetQuery(con, "select 1"))
'data.frame':	1 obs. of  1 variable:
 $ 1:integer64 1 
```

`odbc` returns `integer` with the same query. Personally, I think it is better to return integer64 only when it is necessary because the behavior of integer64 is in some aspects different from base R, e.g. integer64 times a double does not auto-convert to double.

**Comment by krlmlr** [comment]
Thanks. This depends on the database library. The current behavior has type stability, returning different types depending on the data has other, more severe problems. Please use `dbConnect(bigint = "numeric")` or any other option.

@jimhester: Can you please remind me why _odbc_ returns an integer by default?

**Comment by jimhester** [comment]
In odbc this actually depends on how the backend returns the column type of scalar integers. For Postgres this is a regular integer, for MySQL it returns a BIG64 type, so is an integer64. 

We discussed this in https://github.com/r-dbi/DBItest/issues/133 awhile ago.

**Comment by krlmlr** [comment]
Thanks. Sticking with type stability here, it seems easy enough to override.

Happy to discuss improvement of the tests so they make more sense in the _DBItest_ repo.
