### ISSUE TITLE
SSL Connection Error: Access denied

### ISSUE THREAD

**Issue by AhuPersonal** [r-dbi/RMariaDB#115]
Hi,

I am able to connect to mysql database from a SQL workbench with the following settings:

> jdbc:mysql://myhostname:3306/mydbname?verifyServerCertificate=false&useSSL=true&requireSSL=true

When I try to connect with RMariaDB, I get **Access Denied error**. How can I pass `?verifyServerCertificate=false&useSSL=true&requireSSL=true` arguments into the following code ?

```
library(RMariaDB)
con <-dbConnect(RMariaDB::MariaDB(), dbname = "mydbname sslmode=require",
                host = myhostname, 
                port = 3306,
                user = myusername, 
                password = mypassword)
```

**Comment by krlmlr** [comment]
Thanks. Can you use a configuration file via `dbConnect(default.file = "/path/to/my.cnf")` ?
