### ISSUE TITLE
Consider respecting time zone of server

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RMariaDB#116]
Instead of setting the time zone, we could query it via

```sql
SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP)
```

(from https://stackoverflow.com/a/3984412/946850) and add a `"tzone"` attribute to the times returned.

https://github.com/r-dbi/RMariaDB/issues/93#issuecomment-450565902

## Time zones are a mess

From https://github.com/r-dbi/RMariaDB/issues/80#issuecomment-353309883: RMariaDB doesn't set the `"tzone"` attribute for the date-times values it returns. This means that R will display times in your local time zone by default. Date values don't seem to have such an attribute:

``` r
library(DBI)
con <- dbConnect(RMariaDB::MariaDB())
zero_time <- dbGetQuery(con, "SELECT from_unixtime(0)")[[1]]
zero_time
#> [1] "1970-01-01 01:00:00 CET"
lubridate::with_tz(zero_time, "UTC")
#> [1] "1970-01-01 UTC"
```

Created on 2017-12-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

## Do settings affect the values we get from the driver? What time zone is the data stored in?

How does the `TIME_ZONE` variable we set affect the times returned?

MySQL doesn't store time zone information in a column/value. Is it always safe to assume that it's UTC or the server's time zone? Need to document the problem and possible solutions. Note that `TIMESTAMP` and `DATETIME` columns have different semantics.

``` r
library(DBI)

con <- dbConnect(RMariaDB::MariaDB(), dbname = "test")
dbWriteTable(
  con, "test",
  data.frame(timestamp = Sys.time(), datetime = Sys.time()),
  field.types = c("timestamp" = "TIMESTAMP", "datetime" = "DATETIME"),
  temporary = TRUE
)
dbGetQuery(con, "SELECT NOW()")
#>                 NOW()
#> 1 2018-12-30 16:40:53
dbGetQuery(con, "SELECT * FROM test")
#>             timestamp            datetime
#> 1 2018-12-30 16:40:53 2018-12-30 16:40:53

dbExecute(con, "SET time_zone = '-05:00'")
#> [1] 0
dbGetQuery(con, "SELECT NOW()")
#>                 NOW()
#> 1 2018-12-30 11:40:53
dbGetQuery(con, "SELECT * FROM test")
#>             timestamp            datetime
#> 1 2018-12-30 11:40:53 2018-12-30 16:40:53
```

<sup>Created on 2018-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

## Why are DBItest tests not detecting the problems that the users see?

Should the tests require an explicit `"tzone"` attribute for datetime values?

## More info

- https://stackoverflow.com/a/19075291/946850
- https://javorszky.co.uk/2016/06/06/today-i-learned-about-mysql-and-timezones/
- https://dev.mysql.com/doc/refman/8.0/en/datetime.html

## Better documentation

Maybe a separate blog post?

**Comment by jtelleriar** [comment]
Or SELECT @@SESSION.time_zone;

>

**Comment by krlmlr** [comment]
See https://stackoverflow.com/q/2934258/946850 for a case where this is insufficient.

**Comment by krlmlr** [comment]
Add a `timezone` and `timezone_out` argument to `dbConnect()` instead. A value of `NULL` *could* mean that we ask the database, but that's optional.

**Comment by kuty-kajot** [comment]
Hi. I am really clueless what is going on with timezones when querying the database.
Both machine & mysql timezones are the same 

`
> dbGetQuery(con, "SELECT NOW()")
                NOW()
1 2020-01-27 12:52:45
> 
> now()
[1] "2020-01-27 12:53:02 CET"
`

Yet when I query the db (both using dplyr and dbSendQuery) it returns all increased by 1 hour as if translating them from UTC to CET. So the results are correct but the time is incorrectly translated. Setting timezone using `dbExecute` or  by `timezone` and `timezone_out ` arguments within dbConnect() does not make any difference. The results are still translated to +1H.

**Comment by sdittmar** [comment]
Dear Kyrill,

I am experiencing the same effect when trying to read raw data from a database using RMariaDB. Here is my setup:

DB version 10.4.11-MariaDB-1:10.4.11+maria~bionic
R version 3.6.2
DBI_1.1.0
RMariaDB_1.0.8

Regardless of what "@@session.time_zone" is set at, only if I set Sys.setenv(TZ="UTC") in R do I get the data (stored in a datetime column) as original from the database. Is that the intended behavior of RMariaDB?

1) Is RMariaDB assuming that all time data is stored as UTC in the database?

2) Is there a way to keep my local TZ in R and still get the raw data from the DB with the same time as I can see it from other DB managing tools?

Any clarification would be much appreciated.

**Comment by kuty-kajot** [comment]
> Dear Kyrill,
> 
> I am experiencing the same effect when trying to read raw data from a database using RMariaDB. Here is my setup:
> 
> DB version 10.4.11-MariaDB-1:10.4.11+maria~bionic
> R version 3.6.2
> DBI_1.1.0
> RMariaDB_1.0.8
> 
> Regardless of what "@@session.time_zone" is set at, only if I set Sys.setenv(TZ="UTC") in R do I get the data (stored in a datetime column) as original from the database. Is that the intended behavior of RMariaDB?
> 
> 1. Is RMariaDB assuming that all time data is stored as UTC in the database?
> 2. Is there a way to keep my local TZ in R and still get the raw data from the DB with the same time as I can see it from other DB managing tools?
> 
> Any clarification would be much appreciated.

Hi, not a solution (especially if you deal with queries that are time-sensitive and you could not afford the overhead) but a simple work around is to mutate the data column to character on the database side, and reverse it back to date after you collect from the database. I prefer it to messing around with time zone on my machine.

**Comment by krlmlr** [comment]
`timezone` argument is handled in #184.

**Comment by krlmlr** [comment]
Fetching the server's time zone works well enough in https://github.com/r-dbi/RPostgres/pull/276, will add here.

**Comment by krlmlr** [comment]
All problems should be fixed now in the development version, please open a new issue referring this issue if not.
