### ISSUE TITLE
Fix test failures on Windows and Mac

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RMariaDB#117]
https://github.com/r-dbi/RMariaDB/issues/95#issuecomment-450569217 and following.

- [ ] DBItest compatibility
- [x] macOS failures
- [x] Crashes on Win32

**Comment by jeroen** [comment]
Perhaps the issue is not Windows/Mac but a bug or change in recent versions of `mariadb-connector-c`. Currently Windows builds with mariadb-connector-c 2.3.7 and macos builds with mariadb-connector-c 3.0.8.

**Comment by krlmlr** [comment]
Ran a debug build.

The brewed `mysql` instance has this:

```
$ mysql -D test -e "SHOW VARIABLES LIKE 'local_infile'"
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | OFF   |
+---------------+-------+
```

This causes an error with `LOAD DATA LOCAL INFILE` triggered by the "can read file from disk" test.

Skipping the test if detecting this condition in 7af3a2fc32.

**Comment by krlmlr** [comment]
Travis is green now.

**Comment by jeroen** [comment]
OK great. Any luck with debugging Windows? I'd like to know if there is a problem with my driver builds  or if this is just a bug elsewhere.

**Comment by krlmlr** [comment]
Couldn't replicate on Windows. As a last resort I could rdp into the worker, before doing that I'll double-check rtools version and compiler switches.

**Comment by krlmlr** [comment]
Saw a failure with the dev version of _DBI_ and _DBItest_. Will investigate.

**Comment by krlmlr** [comment]
Steps to replicate on 32-bit Windows:

```r
devtools::load_all()
DBItest::test_some("append_roundtrip_timestamp")
```

**Comment by jeroen** [comment]
A timestamp in R should be a double:

```r
> typeof(Sys.time())
[1] "double"
```

So this crash suggests you are using an `int` instead, which will overflow at 2³¹ on 32 bit systems.

**Comment by krlmlr** [comment]
Simplest reprex:

```r
library(DBI)
devtools::load_all()

init_logging("VERB")

con <- dbConnect(RMariaDB::MariaDB(), dbname = "test")

local <- as.POSIXct(2^31, origin = "1970-01-01")
dbGetQuery(con, "SELECT ? AS a", params = list(local))
```

The reason is that `gmtime()` is called with a negative `time_t` value and returns a `NULL` pointer. Need to adopt an alternative implementation already used in _RPostgres_.

**Comment by krlmlr** [comment]
Simply avoiding the crash leads to test failures, unsurprisingly: https://ci.appveyor.com/project/r-dbi/rmariadb/builds/22218641#L797

**Comment by jeroen** [comment]
We're not alone: https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.1-Year-2038-Syscalls

**Comment by krlmlr** [comment]
We should pass `POSIXlt` to the C code instead of calling `gmtime()`.

**Comment by krlmlr** [comment]
https://github.com/r-dbi/RSQLite/pull/333 uses Boost 1.75 for date/time functionality, maybe it's worth investigating.

**Comment by krlmlr** [comment]
The tests on Windows i386 no longer fail, maybe the new Connector/C? :man_shrugging:
