### ISSUE TITLE
Error message tweaking

### ISSUE THREAD

**Issue by hadley** [r-dbi/RMariaDB#118]
Currently:

```R
Error in result_create(conn@ptr, statement, is_statement) : 
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BOOLEAN) AS `y`
FROM `dbplyr_eqginqmosw`
LIMIT 11' at line 1 [1064]
```

So needs C++ equivalent of `call. = FALSE` or C++  in `_RMariaDB_result_create` 

Would also be worthwhile checking why there is leading space before "You have"

**Comment by krlmlr** [comment]
@romainfrancois Do you remember, off the top of your head, the `call. = FALSE` equivalent in _Rcpp_?

**Comment by romainfrancois** [comment]
The easiest is to use -DRCPP_DEFAULT_INCLUDE_CALL=false in the Makevars

**Comment by romainfrancois** [comment]
See https://github.com/tidyverse/dplyr/blob/master/src/Makevars#L2

This makes all Rcpp exceptions not include the call. See https://github.com/RcppCore/Rcpp/pull/868 for the back story.
