### ISSUE TITLE
Error in result_fetch(res@ptr, n = n) : embedded nul in string

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/RMariaDB#121]
I'm working with a table that contains multiple `TEXT` fields. Some of the `TEXT` fields contain `\0` in the middle of the values but RMariaDB does not seem to allow this by throwing an error:

```
Error in result_fetch(res@ptr, n = n) : embedded nul in string: '8\0+|'
```

It would be okay to discard all following characters since `\0` should be regarded as terminating the string.

Previously, the same data was push to a Microsoft SQL Server and I use `odbc` to query the database via FreeTDS driver. The early-terminated strings caused problems too. See https://github.com/r-dbi/odbc/issues/171. Since the data and sync tool are provided by third-party, I can do nothing about the data sources.

**Comment by krlmlr** [comment]
Thanks. Can you cast to binary?

``` r
library(DBI)

con <- DBI::dbConnect(RMariaDB::MariaDB())
dbGetQuery(con, "SELECT 'a\\0b'")
#> Error in result_fetch(res@ptr, n = n): embedded nul in string: 'a\0b'
dbGetQuery(con, "SELECT CAST('a\\0b' AS BINARY)")
#>   CAST('a\\0b' AS BINARY)
#> 1              61, 00, 62
```

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by renkun-ken** [comment]
In my table, the first row that causes this error is the one with `ID = 19267`. 

```sql
select ID, COL1 from mytable where ID = 19267
```

```
Error in result_fetch(res@ptr, n = n) : embedded nul in string: '8\0+|'
```

Then I cast the problematic column as binary:

```sql
select ID, cast(COL1 as binary) from mytable where ID = 19267
```

The row that caused error is represented as follows:

```
38,00,2b,7c
```

However, I need to use `select * from tableX` from an arbitrary number of tables with all their fields. I'm wondering if there's any possibility that `RMariaDB` respect the early termination of such strings and allow user to disable such error.

**Comment by renkun-ken** [comment]
It looks like `Rf_mkCharLenCE` at https://github.com/r-dbi/RMariaDB/blob/98d34198b1c7b8e5ea2f14a112f17eedded15f2e/src/MariaRow.cpp#L137 checks `\0` in the buffer. 

To allow `\0` in the buffer by truncation, `len` must be determined by scanning `\0` in the buffer, which does not look good. I'm not sure if there's better way to allow querying such quirky table.

**Comment by krlmlr** [comment]
I don't have a good answer here. On the one hand, we want resilience, on the other hand we want to know what parts of the data have potential problems. The current solution offers neither.

Do other DBMS allow embedded NUL characters?

I wonder if coercion problems should be reported as attributes of the columns and perhaps as an attribute of the returned data frame. Then, we could flag the invalid values. Other situations are problematic too -- integers with value -2³¹, floats vs. decimals, ...

Would you like to share your use case?

**Comment by renkun-ken** [comment]
I'm using a third-party financial data provider who uses SQL Server to host and publish data. As a client, we use a sync software they provided which is configured to periodically fetch new data from their server and push to our local data server. We have a running SQL Server instance but recently we no longer want to maintain a Windows Server only to host such data so we migrate to MySQL as the sync software also supports push to MySQL. The sync software, however, does not seem to correctly translate SQL Server type (in this case, `uniqueidentifier`, like `uuid` or `guid`) to MySQL counterpart but `varchar` which does not support embedded `NUL` characters. But this field is of no use for us, it's only for internal use.

In this case, if we redefine the table, the sync software won't work. So I'm wondering if there's way to ignore `NUL`s in text fields by truncation or something so that `select * from table` still works.

Fortunately, the data provider has removed the field recently and this problem is gone. If you don't think this needs some discussion, please feel free to close.

**Comment by krlmlr** [comment]
Thanks for your input. I think we should aim for more resilience here, let's keep this open.

**Comment by krlmlr** [comment]
I now think this error message is as good as it gets. If the domains of the data types don't match in R vs. the database, the safest thing is to throw an error. The message provided by base R is good, scanning the string ourselves for embedded NULs just to provide an error message is a lot of effort (computationally and implementation-wise) for limited gain.

**Comment by JulioV** [comment]
Would it be possible to handle this the same way RMySQL does (with a warning instead of an error)? In the project, I maintain NUL characters can appear in multiple rows and this is out of the user's control.

```
Warning message:
In dbFetch(rs, n = n, ...) : internal error: row 865 field 4 truncated
```
