### ISSUE TITLE
system versioned tables

### ISSUE THREAD

**Issue by kkmann** [r-dbi/RMariaDB#124]
Does RMariaDB support system-versioned tables https://mariadb.com/kb/en/library/system-versioned-tables/? Is there any way of doing historical queries in dbplyr?

**Comment by krlmlr** [comment]
Interesting feature.

You should be able to use arbitrary SQL in `dbGetQuery()` and other methods. Maybe [`system_versioning_asof`](https://mariadb.com/kb/en/library/system-versioned-tables/#system_versioning_asof) can help setting the state for a connection?
