### ISSUE TITLE
Use blob class for binary return type

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/RMariaDB#126]
Currently, RMariaDB returns a list of raw vectors from `BINARY` column type. I'm not sure if makes sense that `blob::new_blob()` is called on those binary columns so that they get a class of `blob` which is consistent with the current behavior of `odbc`.

I'm not sure if only binary column can have a list returned. If not, then I cannot tell if a list column is from a binary field or not.

**Comment by krlmlr** [comment]
This looks like an omission, I see no reason why we shouldn't return a blob here.
