### ISSUE TITLE
Adding non-existing columns automatically

### ISSUE THREAD

**Issue by S-UP** [r-dbi/RMariaDB#129]
Hi,

Thanks for your great package!

I am using `dbWriteTable` regularly without creating an SQL table first. That is I create a new table using this function. However, I then do delta updates to this table using the -append- option.

The issue I face is sometimes the new data contains new variables that do not yet exist in the existing database.

Would it be possible to have an option to generate the new variable automatically?

Many thanks!

**Comment by krlmlr** [comment]
Thanks. This feels useful but out of scope of _DBI_. I could imagine this functionality in another package.

**Comment by krlmlr** [comment]
Schema updates on demand are out of scope.

Would your use case permit storing the data in a "longer" form so that you don't need to alter the schema at all?
