### ISSUE TITLE
Bug: Incorrect String Value

### ISSUE THREAD

**Issue by S-UP** [r-dbi/RMariaDB#130]
When executing ```dbWriteTable(con, 'db_name', data_frame, overwrite = T)``` I get the error...

>Error in result_bind(res@ptr, params) : 
  Incorrect string value: '\xEF\xBD\xBB\xEF\xBE\x84...' for column 'VAR' at row 1 [1366]

However, when executing the same command but using RMySQL instead as a driver, then all works fine.

The field in question is a string formatted column, however, the first entry was an NA value.

**Comment by krlmlr** [comment]
Thanks. Can you please share your `data_frame` or even create a [reproducible example](https://reprex.tidyverse.org/)? Are you on Windows?

**Comment by S-UP** [comment]
Hi, 

Unfortunately, I cannot share the original data frame as it contains customer names.

I tried to create a reproducible example, however, using a simple data frame does not throw an error. 

Looking at the original data frame again, I can confirm that the field throwing an error (as stated line 1) is actually a string variable containing an NA value.

Is there anything else I could support you with to identify the issue?

**Comment by krlmlr** [comment]
Thanks. What happens if you try to write the first row, `data_frame[1, ]` ?

**Comment by S-UP** [comment]
So, after some digging: It is not row 1. It seems to be related to Asian characters. It definitively has issues when there are Japanese characters. These characters print fine in the console.

Now I would not know how RMySQL works differently here. But there I do not get an error and all characters are readable later on.

**Comment by krlmlr** [comment]
It would be great to get to the root of the issue, but it's difficult to tell without a reproducible example. If you know which row fails, you can try further minimizing and then obfuscating the data.

**Comment by paulorod7** [comment]
Hi guys, I recently got an error very similar to what happened to @S-UP.
Im my case, my database table was configured with latin1 encode, and my data received had UTF-8.

I resolved my issue using:
dataframe$col <- iconv(dataframe$col, from="UTF-8", to="latin1")
before calling dbWriteTable.

Hope this help someone with similar issue.

**Comment by krlmlr** [comment]
As far as I can tell, we're doing all we can: all strings are converted to UTF-8 before they are sent to the database, and the default connection and client encoding is indeed UTF-8 for both MariaDB and MySQL. I'm not sure why shoehorning into latin1 succeeds. Please open a new issue with more details if problems persist.
