### ISSUE TITLE
dbWriteTable support for Columnstore tables

### ISSUE THREAD

**Issue by manikant-prasad** [r-dbi/RMariaDB#131]
I am using MariaDB Columnstore for a shiny application and need to write small tables to the database. Trying to use dbWriteTable() method for now but the problem is that since the sqlCreateTable from DBI doesn't have an option to specify engine=columnstore at the end of the query, it will create an InnoDB storage engine based table. 

I guess we can add this feature by implementing sqlCreateTable method from DBI in RMariaDB package to accept one extra logical parameter "columnstore" and implementing the SQL as below: 

SQL(paste0(
              "CREATE ", if (temporary) "TEMPORARY ", "TABLE ", table, " (\n",
              "  ", paste(fields, collapse = ",\n  "), "\n)\n ", if (columnstore) "engine=columnstore"
            ))

**Comment by krlmlr** [comment]
Thanks. Table options seem common, PostgreSQL, SQLite and SQL Server also have them. We could provision for a `table_options` argument that is appended to the `CREATE TABLE` query.

**Comment by draben** [comment]
Is there an update to share regarding this feature request? Thx.

**Comment by jtelleriar** [comment]
You could execute:

SET SESSION storage_engine=columnstore


:)

>

**Comment by krlmlr** [comment]
Thanks. I think we can live with that. I don't have columnstore installed on my system, I could change to another storage engine though. Details are at https://mariadb.com/docs/storage-engines/:

``` r
library(RMariaDB)
con <- dbConnect(MariaDB(), dbname = "test")

dbGetQuery(con, "SHOW GLOBAL VARIABLES LIKE 'default_storage_engine'")
#>            Variable_name  Value
#> 1 default_storage_engine InnoDB
tibble::as_tibble(dbGetQuery(con, "SHOW ENGINES"))
#> # A tibble: 8 x 6
#>   Engine     Support Comment                       Transactions XA    Savepoints
#>   <chr>      <chr>   <chr>                         <chr>        <chr> <chr>     
#> 1 CSV        YES     Stores tables as CSV files    NO           NO    NO        
#> 2 MRG_MyISAM YES     Collection of identical MyIS… NO           NO    NO        
#> 3 MEMORY     YES     Hash based, stored in memory… NO           NO    NO        
#> 4 Aria       YES     Crash-safe tables with MyISA… NO           NO    NO        
#> 5 MyISAM     YES     Non-transactional engine wit… NO           NO    NO        
#> 6 SEQUENCE   YES     Generated tables filled with… YES          NO    YES       
#> 7 InnoDB     DEFAULT Supports transactions, row-l… YES          YES   YES       
#> 8 PERFORMAN… YES     Performance Schema            NO           NO    NO
dbExecute(con, "SET SESSION storage_engine=aria")
#> [1] 0
dbWriteTable(con, "test", data.frame(a = 0:1), overwrite = TRUE)
dbReadTable(con, "test")$a
#> [1] 0 1
```

<sup>Created on 2020-12-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
