### ISSUE TITLE
Overflow Issue - Large Unsigned Integers

### ISSUE THREAD

**Issue by dce-crq** [r-dbi/RMariaDB#132]
Would it be possible to add an option in `dbConnect` like ` bigint = c("integer64", "integer", "numeric", "character")` but for regular integers? Default would be integer

Currently R integers are restricted to a signed 32-bit integer. When querying data that has large unsigned integers, we can get overflow issues with integers over 2147483647

```library(RMariaDB)
conn <- dbConnect(MariaDB(), dbname='test', host='localhost')

dbExecute(conn, "CREATE TABLE testing_unsigned_int (reg INT UNSIGNED)")
dbExecute(conn, "INSERT INTO testing_unsigned_int VALUES (2147483647)") 
dbExecute(conn, "INSERT INTO testing_unsigned_int VALUES (4294967295)")

dbGetQuery(conn, "SELECT * FROM testing_unsigned_int")
dbExecute(conn, "DROP TABLE testing_unsigned_int")
```
Above results in 
```
> dbGetQuery(conn, "SELECT * FROM testing_unsigned_int")
         reg
1 2147483647
2         -1
```
In RMySQL, integers were returned as doubles so the signed 32 bit restriction wasn't an issue. Below are environment settings

Using `MySQL 5.6.41-rel84.1` 

sessionInfo()
```R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US       LC_NUMERIC=C         LC_TIME=en_US
 [4] LC_COLLATE=en_US     LC_MONETARY=en_US    LC_MESSAGES=en_US
 [7] LC_PAPER=en_US       LC_NAME=C            LC_ADDRESS=C
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_US LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RMariaDB_1.0.6

loaded via a namespace (and not attached):
[1] bit_1.1-14      compiler_3.5.1  hms_0.4.2       DBI_1.0.0
[5] Rcpp_1.0.1      bit64_0.9-7     pkgconfig_2.0.2 rlang_0.3.2```

**Comment by krlmlr** [comment]
I think this has been added in version 1.0.6?

https://rmariadb.r-dbi.org/reference/dbconnect-mariadbdriver-method

**Comment by dce-crq** [comment]
oh, i see now that my original suggestion was a bit confusing. I was suggesting that an option like this `int = c("integer", "integer64", "numeric", "character")` should be added to the method `dbConnect`. 

I think in version 1.0.6, the option  `bigint = c("integer64", "integer", "numeric", "character")` was added. But that only changes the return type for `BIGINT` SQL data type as you can see below. The overflow issue above happens with the `UNSIGNED INT` SQL data type. 

```
conn <- dbConnect(MariaDB(), dbname='test', host='test', bigint="numeric")
dbExecute(conn, "CREATE TABLE testing_unsigned_int (reg INT UNSIGNED)")
dbExecute(conn, "INSERT INTO testing_unsigned_int VALUES (2147483647)") 
dbExecute(conn, "INSERT INTO testing_unsigned_int VALUES (4294967295)")
dbGetQuery(conn, "SELECT * FROM testing_unsigned_int")
dbExecute(conn, "DROP TABLE testing_unsigned_int")
``` 
Still results in same issue 
```
> dbGetQuery(conn, "SELECT * FROM testing_unsigned_int")
         reg
1 2147483647
2         -1
```

**Comment by krlmlr** [comment]
I see. We have the same problem for 2³¹ -- it's `NA` in R but a valid integer when it comes from the database. But this is not too bad because the `NA` simply indicates that a value was returned that didn't fit the data type. Maybe we need a warning?

Same for unsigned -- we could convert values >= 2³¹ to `NA`, to make the loss of information explicit.

It's especially bad in MySQL/MariaDB because the `CAST()` and `CONVERT()` are so severely limited. Can you use `SELECT col + 0.0` to force coercion to numeric?

The `bigint` argument is a stop gap, I'm not sure we should be adding these arguments for each data type. Rather, we could think about an ALTREP-based implementation that stores the raw data returned from the database library and converts on the fly.

**Comment by krlmlr** [comment]
We should give an error if the data doesn't fit R's native data type, as in #121.

**Comment by krlmlr** [comment]
FWIW, the `bigint` argument is already implemented:

``` r
library(RMariaDB)

con <- dbConnect(MariaDB(), dbname = "test", bigint = "integer64")

out <- dbGetQuery(con, "SELECT 10000000000 AS a")
out
#>             a
#> 1 10000000000
class(out$a)
#> [1] "integer64"
as.numeric(out$a)
#> [1] 1e+10
```

<sup>Created on 2020-08-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Opening a new issue regarding domain mismatch.
