### ISSUE TITLE
RMariaDB Fails to install on RStudio in Ubuntu 18.04

### ISSUE THREAD

**Issue by Pio82** [r-dbi/RMariaDB#133]
RMariaDB library package fails to load. I'm running Ubuntu 18.04 with MySQL 8.0 and RStudio 1.1.463, and R 3.4.4. I ran an apt-get update prior to installing the package just in case.
The last few lines or the error state:

/usr/lib/R/etc/Makeconf:168: recipe for target 'DbResult.o' failed.
make: ***[DbResult.o] Error 1
ERROR: compilation failed for package 'RMariaDB'

    removing '/home/laparic1/R/x86_64-pc-linux-gnu-library/3.4/RMariaDB'
    Warning in install.packages :slight_smile:
    installation of package 'RMariaDB' had non-zero exit status
    The downloaded source packages are in
    '/tmp/RtmpVSmZal/downloaded_packages'

Any help is greatly appreciated. Thanks.

I'm attaching a pdf file with the entire screen result of the failed install.
[RMariaDB_Error.pdf](https://github.com/r-dbi/RMariaDB/files/3055691/RMariaDB_Error.pdf)

**Comment by Pio82** [comment]
Never mind... I figured it out.  I was missing one requirement--libmariadbclient-dev.  I had previously installed libmysqlclient-dev but the RMariaDB install wasn't happy with it. Once I completed the libmariadbclient-dev, which removed libmysqlclient-dev, the installation was successful.

**Comment by sumanth-sirpi** [comment]
Verbatim from theRMariadb installation guide on Github: 

> Installation from source on Linux or OS X currently requires Oracle's libmysqlclient or the more modern MariaDB Connector/C. The latter works best in version 2.3.4/3.0.3 or later, with older versions character and blob columns do not work reliably.

MySQL client library
On recent Debian or Ubuntu install libmysqlclient-dev.

`sudo apt-get install -y libmysqlclient-dev`

Connector/C
On recent Debian or Ubuntu install libmariadb-client-lgpl-dev. In Ubuntu 14.04 this was called libmariadbclient-dev.

`sudo apt-get install -y libmariadb-client-lgpl-dev`
