### ISSUE TITLE
Document preferred client library: MySQL client library or Connect/C

### ISSUE THREAD

**Issue by warnes** [r-dbi/RMariaDB#137]
There appear to be performance differences between using the MySQL client library and Connect/C.   

It would be helpful to have some guidance in the README about which one is preferred.

**Comment by krlmlr** [comment]
Thanks. What performance differences are you seeing?

I can't really recommend which is better. @jeroen: Could you please advise?

**Comment by krlmlr** [comment]
@jeroen: Can we now say that Connector/C is the better client library?

**Comment by jeroen** [comment]
Yes I think mariadb-connector-c is the most actively developes and feature
complete driver. This is also what we use for the binary packages on
Windows and MacOs.

Op vr 25 dec. 2020 18:09 schreef Kirill Müller <notifications@github.com>:
