### ISSUE TITLE
Connection to Memsql

### ISSUE THREAD

**Issue by DarwinCV** [r-dbi/RMariaDB#138]
I'm trying to connect to the MemSql database with the following command

**con <- dbConnect (RMariaDB :: MariaDB (), host = "local", port = 3658,
                  user = "user1", password = "pass", dbname = "tb_cas")**

but I get the following error:

**Error in result_create (conn @ ptr, statement, is_statement):
   Feature 'Audit logging with binary protocol' is not supported by MemSQL. [1706]**

I was using the RMySQL package and I did not have any errors, but I understand that this package is becoming obsolete and RMariaDb is its replacement.

**Comment by krlmlr** [comment]
Thanks. I'm not familiar with MemSQL. 

On the driver level we're using `mysql_stmt_prepare()` or `mysql_real_query()`, without any surprising arguments. I can't relate the arguments to `mysql_real_connect()` to the error message either.
