### ISSUE TITLE
unable to install RMariaDB from source in Mac OS Mojave

### ISSUE THREAD

**Issue by verajosemanuel** [r-dbi/RMariaDB#140]
Trying to solve the issue **Error in result_fetch(res@ptr, n = n) : Error fetching buffer:** on 
 other Macbook R 3.6 Mojave I have, followed instructions here:

https://github.com/r-dbi/RMariaDB/issues/135

everything worked until

`install.packages('RMariaDB', type = "source")`

```
Error: package or namespace load failed for ‘RMariaDB’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Users/jmvaldeolmillos/Library/R/3.6/library/00LOCK-RMariaDB/00new/RMariaDB/libs/RMariaDB.so':
 dlopen(/Users/jmvaldeolmillos/Library/R/3.6/library/00LOCK-RMariaDB/00new/RMariaDB/libs/RMariaDB.so, 6): Library not loaded: libssl.1.0.0.dylib
 Referenced from: /Users/jmvaldeolmillos/Library/R/3.6/library/00LOCK-RMariaDB/00new/RMariaDB/libs/RMariaDB.so
 Reason: image not found
Error: loading failed
```

**Comment by hugo-pa** [comment]
In case anyone else also encounters this error, I too was encountering it on macOS 10.14.6 with R 3.6.1 after following the [instructions](https://github.com/r-dbi/RMariaDB/issues/135#issuecomment-488560838) in the linked issue. 

The only way I was eventually able to get around it was by removing Homebrew and switching to MacPorts. After installing the `openssl` port, I followed uhkeller's [instructions](https://github.com/r-dbi/RMariaDB/issues/135#issuecomment-496294667) and was able to successfully install `RMariaDB` from source.

**Comment by krlmlr** [comment]
Does this still occur with RMariaDB 1.0.8 (released today, macOS binaries should be ready in a few days)?

**Comment by hugo-pa** [comment]
I just installed the macOS binary for RMariaDB 1.0.8 in one of my projects, and it seems that the issue no longer occurs for me on macOS Catalina (10.15.1). Thank you very much!
