### ISSUE TITLE
Error in result_fetch(res@ptr, n, ...) :

### ISSUE THREAD

**Issue by FAMILIALP** [r-dbi/RMariaDB#144]
buenos días, tengo este problema con R, lo estoy corriendo en windows 10 a 64 bits con una conexion normal de ODBC.   
quien me puede ayudar

**Comment by krlmlr** [comment]
This looks like a duplicate of #135. Can you please try installing from source?

**Comment by jeroen** [comment]
I've only updated the mariadb-connector-c driver on macos. We should investigate if the issue also exists with the windows driver.

**Comment by krlmlr** [comment]
@jeroen: Would you mind updating rwinlib, just to be sure?

**Comment by jeroen** [comment]
I don't think this problem existed in the 2.x branch. If you want to jump to the 3.x branch you can send a PR to https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-libmariadbclient/PKGBUILD but note there were breaking changes on Windows from 2.x to 3.x in terms of SSL backends.

**Comment by krlmlr** [comment]
Do you remember any specifics?

I'll do a smoke test on Windows, maybe also with a self-signed SSL certificate.

**Comment by krlmlr** [comment]
Closing for now, please open a new issue if problems persist.
