### ISSUE TITLE
Add a dummy RMariaDB connector

### ISSUE THREAD

**Issue by antoine-sachet** [r-dbi/RMariaDB#146]
This is a feature request.

A dummy connector would be convenient in order to access functions like `dbQuoteIdentifier` and `dbQuoteLiteral`.

For example, I am preparing some SQL queries using `glue::glue_sql` which requires a connection (since it relies on the two functions mentioned above that also take a connection).

```
tbl <- "DB.TABLE"
# I need a con here
con <- DBI::ANSI()

sql <- glue_sql("SELECT * FROM {`tbl`} WHERE sepal_length IN ({vals*})", vals = 1:5, 
                          .con = con)
```

So far I have been using `DBI::ANSI()` which is a dummy ANSI-SQL connection but the quoting is not the same as with a MariaDB connection... Except I don't have a DB to connect to every time I want to prepare a SQL statement.

Can we get something like `RMariaDB::dummyConnection()` or do you have a suggestion to get a con without a live DB?

**Comment by krlmlr** [comment]
Thanks. Unfortunately, the MariaDB library requires a live connection for quoting strings. We're using `mysql_real_escape_string()` under the hood. I don't see how we can make this work.

**Comment by krlmlr** [comment]
This would make a good feature. Unfortunately, I don't have the bandwith to implement this, happy to review a pull request. Perhaps we can replicate the quoting rules in `mysql_real_escape_string()` in R?
