### ISSUE TITLE
Connection parameters in .my.cnf no longer used in version 1.0.7

### ISSUE THREAD

**Issue by kurt-vd** [r-dbi/RMariaDB#148]
I have database / host connection info in `.my.cnf`.
```
[motus]
host=127.0.0.1
```
The following code worked until I upgraded to version 1.0.7.
`result <- RMariaDB::dbConnect(RMariaDB::MariaDB(), group="motus");`

Now I get this error message which seems to indicate that the `.my.cnf` file is not used anymore:
```
Error in connection_create(host, username, password, dbname, as.integer(port),  : 
  Failed to connect: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

I am using R 3.6.1 on Mac OS.

**Comment by krlmlr** [comment]
Thanks. Does it work if you install RMariaDB from source or from GitHub?

**Comment by kurt-vd** [comment]
It's hard to install from source on MacOS.
I need to install development headers for MariaDB library.
I'm not sure how safe that is on MacOS

**Comment by krlmlr** [comment]
RMariaDB 1.0.8 is on CRAN, but not built for OS X yet -- this should happen in a few days. Can you please double-check then?

**Comment by kurt-vd** [comment]
RMariaDB 1.0.8 (required DBI 1.1.0 instead of 1.0.0) works. Thanks
