### ISSUE TITLE
Released version 1.0.7 on CRAN doesn't match git tag

### ISSUE THREAD

**Issue by gitsparky** [r-dbi/RMariaDB#149]
The fix for issue #111 ( PR #107 ) is not present in the tarball for [v1.0.7 on CRAN](https://cran.r-project.org/src/contrib/RMariaDB_1.0.7.tar.gz).

Specifically the file `src/pch.h` is missing the conditional definition of `my_bool` as mentioned in the above PR.

The [same file](https://github.com/r-dbi/RMariaDB/blob/v1.0.7/src/pch.h) in the commit tagged v1.0.7 has the fix.

This is causing all install from source to fail with the same problem as in Issue #111

**Comment by gitsparky** [comment]
The changeset between the tarballs of v1.0.6 and v1.0.7 on CRANR seems too small:

```console
$ diff -q -r v1.0.6/RMariaDB/src v1.0.7/RMariaDB/src
Files v1.0.6/RMariaDB/src/DbResult.cpp and v1.0.7/RMariaDB/src/DbResult.cpp differ
Files v1.0.6/RMariaDB/src/connection.cpp and v1.0.7/RMariaDB/src/connection.cpp differ
```

whereas in the git repo:

```console
$ git diff --stat v1.0.6 src
 src/DbConnection.cpp      |   9 +++++++++
 src/DbConnection.h        |   1 +
 src/DbResult.cpp          | 105 +++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------
 src/DbResult.h            |  43 ++++++++++++++++++++-----------------------
 src/DbResultImpl.h        |   2 ++
 src/DbResultImplDecl.h    |   2 ++
 src/Makevars.in           |   2 +-
 src/Makevars.win          |  14 ++++++++++----
 src/MariaBinding.cpp      |  10 +++++++---
 src/MariaBinding.h        |   3 ++-
 src/MariaResult.cpp       |  32 ++++++++++++++++++++++++++++++++
 src/MariaResult.h         |  20 ++++++++++++++++++++
 src/MariaResultPrep.cpp   |  23 ++++++++++++-----------
 src/MariaResultPrep.h     |  11 +++++++----
 src/MariaResultSimple.cpp |  15 ++++++---------
 src/MariaResultSimple.h   |   8 +++++---
 src/MariaRow.h            |   3 ++-
 src/connection.cpp        |  21 ++++++++++++---------
 src/pch.h                 |   4 ++++
 src/result.cpp            |   3 ++-
 20 files changed, 207 insertions(+), 124 deletions(-)
```

**Comment by krlmlr** [comment]
I did a patch release to support newer compilers with warnings, off of the `v1.0.6` tag. Will release DBI and an update to RMariaDB soon.

**Comment by gitsparky** [comment]
For now, we reverted the system MySQL libs to v5.x and all is working again, but updated version of RMariaDB compatible to v8.x would be nice to have.

For my info: the git tag name isn't expected to match the CRAN release version?

**Comment by krlmlr** [comment]
I updated the tag, the local version and the GitHub version were off. Thanks for catching this!

Are the tags now as expected?
