### ISSUE TITLE
connecting using SSL (client.flag=2048) to a RDS DB freezes forever from some computers

### ISSUE THREAD

**Issue by kforner** [r-dbi/RMariaDB#151]
I'm using an aws RDS DB (MySQL 5.6). I created an account which requires SSL.
`GRANT USAGE ON *.* TO 'xxx'@'%' REQUIRE SSL;`

I can successfully connect to this DB account using RMySQL or RMariaDB using the `client.flag=2048` dbConnect param from some computers. 
But from others, R just freezes forever in dbConnect. 

What could be the problem ? The RMySQL/RMariaDB version ? The mysql/mariaDB client version ? 

I checked the connectivity to the DB using telnet...

Thanks.

**Comment by kforner** [comment]
I checked that from one computer that is freezing, I can connect successfully using the `mysql` cli client.

**Comment by kforner** [comment]
I made a reproducible example featuring a SSL-enabled MySQL server and R install: 
https://github.com/kforner/mysql_ssl_r_connect_bug

Should I open an issue in RMySQL too ? 

Thanks.
Karl

**Comment by kforner** [comment]
Hello, 
Any comment on this ? 
I spent a lot of time providing a complete reproducible example with the mysql server and clients configured...

**Comment by krlmlr** [comment]
Thanks, this slipped through the cracks.

Will investigate, at rstudio::conf now.

**Comment by krlmlr** [comment]
The connection process hangs at `connection_create()`. Under the hood, `mysql_real_connect()` is called. The [documentation](https://dev.mysql.com/doc/refman/8.0/en/mysql-real-connect.html) suggests that using `CLIENT_SSL` (2048) is not a good idea:

> Do not set this option within an application program; it is set internally in the client library. Instead, use ... `mysql_ssl_set()` before calling `mysql_real_connect()`. 

This function is called if you set one of the `ssl.` arguments to `dbConnect()`. Do we need to create a client certificate in the R container?

**Comment by kforner** [comment]
When you use the `mysql` command-line client, you do not need to give any SSL certificate/key/bundle whatever to connect using SSL. 

So why would we need to give any to MariaDB `dbConnect()` ?

**Comment by krlmlr** [comment]
I have tried `mycli` in the R container (had to install it), but I haven't found the certificates in that container: `/etc/certs` doesn't exist there.

**Comment by kforner** [comment]
Does `mycli` complains about `/etc/certs` ?


Additionally, from the doc:
> It is optional to call mysql_ssl_set() to obtain an encrypted connection because by default, MySQL programs attempt to connect using encryption if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established (see Section 6.3.1, “Configuring MySQL to Use Encrypted Connections”). mysql_ssl_set() may be useful to applications that must specify particular certificate and key files, encryption ciphers, and so forth. 

From what I understand, it should automatically connect using SSL, right ?

**Comment by krlmlr** [comment]
I tried using `mysql` from the MySQL server container, run with `docker-compose exec mysql bash`, with no success:

```
# mysql -h mysql -u ssltest --ssl -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'ssltest'@'172.18.0.2' (using password: YES)
```

What am I missing?

**Comment by kforner** [comment]
> What am I missing?

Nothing, I checked again and got the same result as you just did.
 
I kind of remember I had not tested with this mysql server but with an AWS aurora DB...
Maybe there's some standard certificates involved... Or I just messed it.

I'll try again supplying the certificates with RMariaDB, because it seems that with RMySQL the ssl params are not used, cf the processing of `...` in
https://github.com/r-dbi/RMySQL/blob/master/R/connection.R#L66

Thanks for your time.

**Comment by kforner** [comment]
I updated the example so that the certificates are accessible from the r container.
This now works:
```
db <- dbConnect(MariaDB(), host = 'mysql', user = 'ssltest', password='ssltest', ssl.ca = '/mysql/ca.pem', ssl.key = '/mysql/server-key.pem', ssl.cert = '/mysql/server-cert.pem')
```

But this does not:
```
db <- dbConnect(MySQL(), host = 'mysql', user = 'ssltest', password='ssltest', ssl.ca = '/mysql/ca.pem', ssl.key = '/mysql/server-key.pem', ssl.cert = '/mysql/server-cert.pem')
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'ssltest'@'172.20.0.2' (using password: YES)
```

I still have some questions:

- on some setups, I could connect with **RMySQL** using SSL without freezing and without supplying any SSL certificate. Was it because the mysql client could find those certificates automatically somewhere on the system ?
- do you know how to connect with **RMariaDB** using the SSL certificate bundle as supplied by Amazon for Aurora DB ? 

Thanks a lot for your help.
Karl

**Comment by krlmlr** [comment]
Sorry for my very slow reply.

Just tried your example once again, works for me with RMariaDB.

I suspect that the client library knows how to look in "standard" certificate locations, I'm not sure though. I don't have experience with Aurora DB.
