### ISSUE TITLE
Cannot disable SSL when connecting to MySQL-Server

### ISSUE THREAD

**Issue by jarauh** [r-dbi/RMariaDB#152]
I'm trying to connect to a MySQL-5.7-Server without SSL.  Since I updated MySQL on my client to version 8.0, opening a connection using RMariaDB does not work anymore as before.

The client works, if I disable SSL-mode explicitly:
```
mysql -h 10.20.0.90 --ssl-mode=DISABLED -u username -p<PWD>
```

The following does not (which used to work earlier):
```r
> DBI::dbConnect(RMariaDB::MariaDB(), host = "10.20.0.90", user = ..., password = ...)
Fehler: Failed to connect: SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
```
I tried to add the following to my .my.cnf, but it did not help:
```
[client]
host=10.20.0.90
port=3306
user=<username>
password=<PWD>
ssl-mode=DISABLED
```

Any help is appreciated!

**Comment by jarauh** [comment]
One problem might be a difference between MySQL and MariaDB: Apparently, there is a MySQL-Option MYSQL_OPT_SSL_MODE (https://dev.mysql.com/doc/refman/8.0/en/mysql-options.html) that does not exist in MariaDB (https://mariadb.com/kb/en/mysql_optionsv/).  Is there a corresponding option that I could use?

**Comment by grooverdan** [comment]
Recommend requesting this option - https://jira.mariadb.org/ CONC project.

**Comment by estraviz** [comment]
Hi, @jarauh and everyone, did you manage to solve this issue? Not working for me either although I'd used the same options in my $HOME/.my.cnf file. I'm trying to connect to an external MySQL from R in a docker container (rocker/tidyverse image). Thanks.

**Comment by grooverdan** [comment]
MYSQL_OPT_SSL_ENFORCE or as a config option `ssl-enforce=0`

ref: https://mariadb.com/kb/en/mysql_optionsv/#tls-options

If any other ssl option is given, ssl is used always. https://github.com/mariadb-corporation/mariadb-connector-c/blob/3.1/plugins/auth/my_auth.c#L227

**Comment by jarauh** [comment]
Hi @javier, I did not have time to look into it and just downgraded my MySQL-client.
 

Gesendet: Freitag, 17. Juli 2020 um 19:54 Uhr
Von: "Javier Estraviz" <notifications@github.com>
An: "r-dbi/RMariaDB" <RMariaDB@noreply.github.com>
Cc: "jarauh" <jarauh@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [r-dbi/RMariaDB] Cannot disable SSL when connecting to MySQL-Server (#152)


 

Hi, @jarauh and everyone, did you manage to solve this issue? Not working for me either although I'd used the same options in my $HOME/.my.cnf file. I'm trying to connect to an external MySQL from R in a docker container (rocker/tidyverse image). Thanks.

**Comment by krlmlr** [comment]
Thanks for the input. Why is it important to disable SSL?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
