### ISSUE TITLE
CLIENT_COMPRESS problem?

### ISSUE THREAD

**Issue by elfatherbrown** [r-dbi/RMariaDB#153]
I had everything working until I had the great idea to turn on the client compress flag as such:
MY_POOL=pool::dbPool(RMariaDB::MariaDB(),
                               client.flag=CLIENT_COMPRESS)

My database is very big, it does heavy computation. Everything was working until I had that idea. After that, on every collect() I got:
 big_coomputation()%>%collect(n=Inf)
Error: Lost connection to MySQL server during query [2013] 

After that mysql server gone away and etc... I had nothing interesting in my my.cnf except the packet size set to 1gb. Turned off CLIENT_COMPRESS and its all happy now. 

Man that was scary.

Sorry to not be of more help here, or if this is obvious to someone. Just thought id pass on this problem here to see if it rings a bell.

**Comment by krlmlr** [comment]
Thanks for the heads up. Not all client flags necessarily make sense with RMariaDB. What was your motivation for turning on client compression?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
