### ISSUE TITLE
Authentication plugin 'mysql_clear_password' cannot be loaded

### ISSUE THREAD

**Issue by vigyoyo** [r-dbi/RMariaDB#158]
I am trying to connect to an AWS RDS MySQL database that has IAM authentication enabled. I am getting this error when trying to connect:
Error: Failed to connect: Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled

dbConnect(
                                RMariaDB::MariaDB(), 
                                username='', 
                                password=token, 
                                dbname='', 
                                host='',
                                port=
                           )

**Comment by krlmlr** [comment]
Thanks. Could you point me to documentation that describes how to connect to such a database, e.g. from the command line?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
