### ISSUE TITLE
tbl() %>% collect() fails

### ISSUE THREAD

**Issue by ericemc3** [r-dbi/RMariaDB#161]
That instruction fails with `drv = MariaDB()` (though it works with `drv = MySQL()`)
Here provinces_test is a table in a MySQL database:
```r
tbl( mycon, "provinces_test") %>% collect()
#You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"provinces_test" AS `zzz19`
WHERE (0 = 1)' at line 2 [1064]
```
it looks like the SQL request sent is: 
SELECT * FROM "provinces_test" AS `zzz19` WHERE 0 = 1 
since i get the same error message if i run it manually

Error Code: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"provinces_test" AS `zzz19` WHERE 0 = 1 

With `drv = MySQL()` i get :
```r
# A tibble: 3 x 2
  province code 
  <chr>    <chr>
1 Málaga   MA   
2 Córdoba  CO   
3 Cádiz    CA   
```

**Comment by krlmlr** [comment]
Thanks. Can you please try the latest dev version of dbplyr?

**Comment by ericemc3** [comment]
Thanks for your prompt reply!
I have trouble (Windows) with
devtools::install_github("tidyverse/dbplyr")
(as with devtools::install_github("tidyverse/dplyr"

=> circularity issues with glue that cannot be updated...
cannot remove prior installation of package ‘glue’

i have already spent hours on this trying to update to the last dplyr dev...

**Comment by ericemc3** [comment]
I managed to have dbplyr dev installed (with rtools4 and a little patience).

I confirmed it is fixed, thanks!
