### ISSUE TITLE
Connecting using SSL but without verifying the certificate

### ISSUE THREAD

**Issue by oriolcmp** [r-dbi/RMariaDB#164]
Hello,

I need to connect to a server through a port that uses SSL. The certificate used is not supposed to be verified. In the command line this is possible by only doing:

mysql --ssl -h <HOST> -P 6033 ....

If I was doing the same but:

mysql --ssl -h <HOST> -P 6033 **--ssl-verify-server-cert** ....

Then it checks the certificate. Therefore, I would like to start a connection through RMariaDB but avoiding the certificate check (First option). 
Is that possible? What are the parameters in RMariaDB to make this possible?
Thanks,

**Comment by krlmlr** [comment]
Thanks. This seems to correspond to the `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` option, which seems off by default. What does your `dbConnect()` code look like now?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
