### ISSUE TITLE
Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by samuel-cs4** [r-dbi/RMariaDB#166]
I'm getting this error `Erro: Commands out of sync; you can't run this command now [2014]` when I call an Stored Procedure. 

Only solution I found is to close the connection in between the calls but it is not viable for my application (Shiny). I found this [Issue](https://github.com/r-dbi/RMySQL/issues/163) on deprecated library `RMySQL` but this 'solution' doesn't work on this library.

```r
con <- dbConnect(RMariaDB::MariaDB(),
                 user     = 'user',
                 password = 'password',
                 dbname   = 'db_name',
                 host     = 'host' )

# This works the first time
rs <- dbGetQuery(con, "CALL stored_procedure()")

# This doesn't works again
new_rs <- dbGetQuery(con, "CALL stored_procedure()")

# And that doesn't work either
new_query <- dbGetQuery(con, "SELECT 1")
```

The only alternative is to uso the deprecated library `RMySQL`?

**Comment by krlmlr** [comment]
Does it work if you use `dbExecute()` instead of `dbGetQuery()`?

Can you post the code of the stored procedure? Does it return multiple result sets as suggested in https://github.com/r-dbi/RMySQL/issues/163?

**Comment by samuel-cs4** [comment]
If I use `dbExecute` the result set is `-1`.

And yes, the Stored Procedure return multiple result sets.

**Comment by krlmlr** [comment]
I'm not familiar with MySQL stored procedures. Could you please give an example of a simple SP that returns two result sets, so that we can create a reproducible example?

**Comment by krlmlr** [comment]
Does it help to use one of:

- `client_flag = CLIENT_MULTI_STATEMENTS`
- `client_flag = CLIENT_MULTI_RESULTS`
- `client_flag = CLIENT_MULTI_STATEMENTS + CLIENT_MULTI_RESULTS`

in `dbConnect()`?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
