### ISSUE TITLE
RMariaDB Fails to install on RStudio in Ubuntu 20.04

### ISSUE THREAD

**Issue by verajosemanuel** [r-dbi/RMariaDB#168]
Followed instructions from theRMariadb installation guide on Github:

`
# libmysqlclient-dev
sudo apt-get install -y libmysqlclient-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmysqlclient-dev is already the newest version .
0 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.

# Connector/C
sudo apt-get install -y libmariadb-client-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libmariadbclient-dev-compat' for regex 'libmariadbclient-dev.'
Note, selecting 'libmariadb-dev-compat' instead of 'libmariadbclient-dev-compat'
libmariadb-dev-compat is already the newest version (1:10.3.22-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.
`

Rstudio installation error:

Error: package or namespace load failed for ‘RMariaDB’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jose/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-RMariaDB/00new/RMariaDB/libs/RMariaDB.so':
  libmysqlclient.so.20: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/3.6/RMariaDB’
Warning in install.packages :
  installation of package ‘RMariaDB’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpbC63xE/downloaded_packages’

**Comment by krlmlr** [comment]
Thanks. I tried with a fresh install of Ubuntu Focal. There seems to be no `libmariadb-client-dev` in the default repositories, I could flawlessly build RMariaDB with `libmysqlclient-dev`.

If the problem persists, can you please run `locate libmysqlclient.so` ?

**Comment by krlmlr** [comment]
Bionic and Focal have `libmariadbclient-dev` (without the dash).
