### ISSUE TITLE
Error Code: 2013. Lost connection to MySQL server during query, when deleting initid->ptr

### ISSUE THREAD

**Issue by Sahil308** [r-dbi/RMariaDB#177]
I am trying to create a MySQL aggregate UDF.
In the void xxx_deinit(UDF_INIT *initid) function I am releasing any memory used, which in my case is char*.

In the bool xxx_init(UDF_INIT *initid, UDF_ARGS *args, char *message) I am assiging a char* to initid->ptr, like this:

```
extern "C" bool xxx_init(UDF_INIT * initid, UDF_ARGS * args, char* message)
{
    const char*  demo = "demo";

    initid->ptr = (char*) demo;

    return 0;
}
```

my deinit method looks like this:

```
extern "C" void xxx_deinit(UDF_INIT * initid)
{
    delete initid->ptr;
}
```
After creating and installing the aggregate udf in mysql, when i try to execute it an error message pops up stating:

> Error Code: 2013. Lost connection to MySQL server during query

But when I remove the statement `delete initid->ptr;` from the xxx_deinit function(UDF_INIT * initid), I get my desired result.

I am not able to figure out the problem here.
Can anyone help me out with this?
Why is it occurring?
What am i doing wrong here?
Any suggestions or guidance will be of great help.
Thanks in advance.

**Comment by krlmlr** [comment]
Thanks. This problem doesn't seem to be related to the RMariaDB R package, our issue tracker is not the right forum for this kind of problem.

The `delete` operator must be called only on pointers allocated with `new`.
