### ISSUE TITLE
Connection:  is connected, reconnect on disconnect, etc

### ISSUE THREAD

**Issue by MonteShaffer** [r-dbi/RMariaDB#181]
Where is the method `checkConnectionStatus` that returns TRUE/FALSE ?

I can adjust the `timeout`, I get that, but when I create a connection, the user/password is stored, so is there a `reconnectOnDisconnect()` that gets called if the `checkConnectionStatus` had dropped the line.

I guess I could write my own wrapper function `checkConnectionStatus` with `tryCatch` as I read somewhere online `dbGetQuery(con, "SELECT CURRENT_TIMESTAMP;")`

Seems like this should be part of the core code base.

Thoughts?

**Comment by MonteShaffer** [comment]
Please see <https://github.com/MonteShaffer/humanVerseWSU/blob/master/humanVerseWSU/R/functions-mysql.R> for some `tryCatch` attempts to address what the core library should be...

Save connection information, try to reconnect, and check connection status ...

**Comment by krlmlr** [comment]
Does `dbIsValid()` work for your use case?

Connection information can be stored in connector objects, see the corresponding section in https://www.r-dbi.org/blog/dbi-3-2/.

I'd rather avoid automatic reconnection due to the (repeated) timeouts this may lead to.

**Comment by krlmlr** [comment]
Let's discuss automatic reconnection in #142.
