### ISSUE TITLE
Authentication fails because caching_sha2_password.dll doesn't exist

### ISSUE THREAD

**Issue by arencambre** [r-dbi/RMariaDB#182]
When running this:

```r
test_db <- dbConnect(RMariaDB::MariaDB(),
                       user='username',
                       password='password',
                       dbname='my_database',
                       host='localhost')
```
It fails with this error:
```
Error: Failed to connect: Plugin caching_sha2_password could not be loaded: The specified module could not be found.
```

It is apparently looking for **caching_sha2_password.dll** in all directories in my path:
![image](https://user-images.githubusercontent.com/411495/97804863-1d390100-1c18-11eb-8af9-2d70504db020.png)

This won't work because the DLL does not exist. This is confirmed by a post of Georgi "Joro" Kodinov, MySQL SrvGen team lead, at https://forums.mysql.com/read.php?10,664655,664726. I have MySQL Connector C++ 8.0 installed, and I can confirm that this DLL is not included. (Yes, it's true that the path doesn't touch those the MySQL Connector's directories, but that's not relevant, since the file doesn't exist.)

Others have reported this error. Here's an example, which includes a workaround that appears to downgrade security: https://stackoverflow.com/questions/54099722/how-to-connect-r-to-mysql-failed-to-connect-to-database-error-plugin-caching

I am running R 4.0.3 on Windows 10 2H20 with all R packages up to date.

While this seems to relate to #134, I am not sure it's the same. If it overlaps, then this issue provides some specific guidance to that other issue, at least for Windows users.

**Comment by krlmlr** [comment]
Thanks for reporting. For Windows we need to change the static library, I've filed an issue.

**Comment by jeroen** [comment]
@arencambre can you please try this again with the latest CRAN release (RMariaDB 1.0.11)

**Comment by arencambre** [comment]
I am able to connect now. Thank you.
