### ISSUE TITLE
`~` not resolved correctly in `default.file` argument

### ISSUE THREAD

**Issue by twentytitus** [r-dbi/RMariaDB#197]
Hi,

on Windows 10 with R 4.0.2, after updating from RMariaDB 1.0.8 to 1.0.11, the following fails:

```r
library(RMariaDB)
dbConnect(MariaDB(), groups = "MYSQL", default.file = "~/.my.cnf")
```

The error message is `Failed to connect: Can't connect to MySQL server on 'localhost' (10061)`.

However, replacing the `~` as in 

```r
dbConnect(MariaDB(), groups = "MYSQL", default.file = file.path(Sys.getenv("R_USER"), ".my.cnf"))
```

works just fine. Any ideas why this could happen? The issue was not present before the package update. Edit: It also seems to work with version 1.0.10.

Many thanks in advance!

**Comment by krlmlr** [comment]
Thanks. On Windows, the Connector/C version was upgraded from 2.3.7 to 3.1.11, perhaps the change is related.

We could call `normalizePath()` on the R side to restore the old behavior. Would you like to submit a pull request?

**Comment by twentytitus** [comment]
I can give it a try next week!
