### ISSUE TITLE
NULL values in BIT(1) columns are returned as TRUE

### ISSUE THREAD

**Issue by dirkschumacher** [r-dbi/RMariaDB#201]
It seems that with version 1.1.0 `BIT(1)` columns that have `NULL` values return `TRUE` instead of `NA`. This might be a bug introduced in #192.

```r
library(RMariaDB)
con <- dbConnect(MariaDB(), dbname = "test")
dbWriteTable(con, "test", data.frame(a = c(NA_integer_, 0:1)), field.types = c(a = "BIT(1)"), overwrite = TRUE)
dbReadTable(con, "test")$a
#> [1] TRUE FALSE TRUE
```

The `dbWriteTable` call creates a table with the below CREATE statement. The table on the server does contain the values `NULL`, `0` and `1` on my MySQL instance (version 8).
```sql
CREATE TABLE `test` (
  `a` BIT(1) NULL DEFAULT NULL
)
```

The problem might be here, where `NA_INTEGER` is mapped to `1` it seems.
https://github.com/r-dbi/RMariaDB/blob/524135500b37790b33b895416d14613ee9874321/src/MariaRow.cpp#L216-L218

Happy to contribute a fix and thanks for all your work!

**Comment by krlmlr** [comment]
Good catch, what an evil glitch. I agree with your analysis, happy to review a PR!
