### ISSUE TITLE
RMariaDB returns a query without microseconds

### ISSUE THREAD

**Issue by bakiunal** [r-dbi/RMariaDB#214]
Hi

I created a table with following sql code:

CREATE TABLE pp_guniciislem201906.pp_201906 (
    date DATE,
    transaction_code VARCHAR(15),
    joint_agree_no VARCHAR(20),
    match_trade_item VARCHAR(15),
    buy_sell VARCHAR(15),
    num_transactions INT,
    paid_price FLOAT,
    trade_value FLOAT,
    order_no VARCHAR(20),
    trade_time TIME(6),
    trade_report INT,
    session VARCHAR(20),
    trade_status INT,
    settlement_date VARCHAR(5),
    assets_liabilities VARCHAR(1),
    trade_id INT,
    deal_id INT,
    update_time DATETIME,
    give_up_flag VARCHAR(1),
    update_no INT,
    update_time2 DATETIME    
);

I defined "trade_time" column with "TIME(6)". Because I have only time such as "09:55:02.113000" but not date.
Then I imported a csv file data to table with following sql code:

LOAD DATA INFILE 'G:\m201906.csv'
INTO TABLE pp_guniciislem201906.pp_201906
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 2 ROWS;

After that, when I query "SELECT * FROM pp_guniciislem201906.pp_201906;" "trade_time" column displays with fractional seconds. (I attached screenshot of mysql screen)

Then when I query from r with following code I could not get fractional seconds. I attached Rstudio screenshot image. As seen from this image in "trade_time" column fractional seconds are gone.

library(RMariaDB)

my_date <- '2019-06-24'

my_transaction_code <- 'AKBNK.E'

pp_201906 <- dbConnect(RMariaDB::MariaDB(), user='root', password='qazwsxedc', dbname='pp_guniciislem201906', host='localhost')

myquery <- paste("SELECT * FROM pp_201906 WHERE date='",my_date,"' AND transaction_code='",my_transaction_code,"'", sep="")

rs = dbSendQuery(pp_201906, myquery)

dbRows<-dbFetch(rs)

How can I solve this problem.
Best Regards

![mysql](https://user-images.githubusercontent.com/36884503/127326757-8fa5ec56-4033-4bee-a4d0-1a4b4cccb0e9.jpg)
![rstudio](https://user-images.githubusercontent.com/36884503/127326802-9c603696-9dde-40b6-90c7-8c609d76ea88.jpg)

**Comment by krlmlr** [comment]
Thanks, confirmed:

``` r
library(DBI)
library(RMariaDB)

con <- dbConnect(RMariaDB::MariaDB(), dbname = "test")

time <- structure(1629770306.84675, class = c("POSIXct", "POSIXt"))
time_df <- data.frame(time)

dbWriteTable(con, "test", time_df)
time_df_out <- dbReadTable(con, "test")

waldo::compare(time_df, time_df_out)
#> `attr(old$time, 'tzone')` is absent
#> `attr(new$time, 'tzone')` is a character vector ('UTC')
#> 
#> `old$time`: 1629770306.8
#> `new$time`: 1629770306.0

dbRemoveTable(con, "test")
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by krlmlr** [comment]
Do you need to create `update_time2` and other columns as `DATETIME(6)` to actually store microseconds?

I'll change the default in RMariaDB.
