### ISSUE TITLE
Installation failure on UCRT

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RMariaDB#234]
https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/RMariaDB-00install.html

```
* installing *source* package 'RMariaDB' ...
** package 'RMariaDB' successfully unpacked and MD5 sums checked
** using staged installation
** applying installation-time patches
The next patch would create the file src/Makevars.ucrt,
which already exists!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
WARNING: failed to apply patch patches/CRAN/RMariaDB.diff
```

@jeroen: Is this something we need to fix in rwinlib?

**Comment by jeroen** [comment]
You can ignore this warning. It will disappear automatically when CRAN removes your package from the list of packages that need manual patching. The installation still succeeds.

**Comment by krlmlr** [comment]
Thanks!
