### ISSUE TITLE
`dbAppendTable(con, Id(...), data)` no longer works

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/RMariaDB#253]
`Id(schema = "foo", table = "bar")` could be used as `name` argument in a number of functions, as documented at https://github.com/r-dbi/DBI/blob/main/R/Id.R. However, the latest release no longer seems to support `Id` at all. Whenever I supply a `Id(...)`, the following error occurs, say that it must be a character vector.

```
Error in dbAppendTable(con, id, data) : 
  is.character(name) is not TRUE
```

Am I missing something?

**Comment by krlmlr** [comment]
Thanks. This is a bug, we should be calling `dbQuoteIdentifier()` .

**Comment by renkun-ken** [comment]
Thanks for confirming this. It breaks my production code, so I must roll back to the previous version.

A bit surprised that the usage is not covered in the test cases.

**Comment by krlmlr** [comment]
The tests don't test explicitly that `Id()` objects can be passed. I agree that if the documentation claims it that we should also test for it. Might lead to breaking changes elsewhere.

Both `dbWriteTable()` and `dbAppendTable()` are affected.

**Comment by krlmlr** [comment]
Did it work before with  `dbAppendTable()`? It looks like this particular method never supported `Id()` .

Please work around for now -- quote manually before calling `dbAppendTable()` . This will continue to work after the update.

**Comment by renkun-ken** [comment]
I use `dbAppendTable()` and `dbWriteTable()`, `dbListFields()` etc. with `Id()` for at least two years, if not more.

At least all the listed functions at <https://github.com/r-dbi/DBI/blob/main/R/Id.R#L13> support `Id()` in the the previous CRAN release. I think it should be regarded as an important breaking change as the document in `Id` still claims that it is supported in these functions.
