### ISSUE TITLE
RMariaDB failed to connect to db 

### ISSUE THREAD

**Issue by EllyJung** [r-dbi/RMariaDB#264]
Hi I am using Rstudio on my MacBook, I connected MariaDB server by terminal and it connected well, but when i try to run a code below, it does not work. 

```r

# set file_path ---------------------------------------------------------------
file_path <- glue("../Users/xxxxxxx/Desktop:/{list.files('../Users/xxxxxxxx/Desktop:/', pattern = 'xxxxxxxxx')}/")

args <- read.delim(paste0(file_path, "con_names.txt"), sep = ",", header = F)
getwd()
db_input <- args$V1
user_input <- args$V3
pw_input <- args$V4
host_input <- args$V5

con <- dbConnect(MySQL(),
                 dbname = db_input, 
                 user = user_input,
                 password = pw_input,
                 host = host_input)
```
but console shows me this error:
```r
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'root'@'localhost'
```
By the way, I installed MariaDB by home-brew also tried change my_native_password. but still did not work. 
Please advise anything if there is any solution for this. Thanks!

**Comment by krlmlr** [comment]
Thanks, this fell through the cracks. Have you managed to connect from R? What package did you end up using?
