### ISSUE TITLE
unable to find an inherited method for function 'dbFetch' for signature '"character"'

### ISSUE THREAD

**Issue by arecibo** [r-dbi/RMariaDB#268]
I am using R-4.1.2 on OSX-12.3.1 (Apple Silicon), along with RMariaDB-1.2.1 and DBI-1.1.2.
My MariaDB versions on remote server (Ubuntu 20.04) and local machine are both 10.7.3.
 
The following commands produce error messages.

```r
con <- dbConnect(RMariaDB::MariaDB(),
                     user='user',
                     password='password',
                     host='host',
                     port=3306
                     dbname='my-db')
query <- "SELECT * FROM sapi WHERE person_address_id = 400"
rs <- dbSendQuery(con, query)
tmp <- dbFetch(query, n = -1)
## Error in (function (classes, fdef, mtable)  : 
##   unable to find an inherited method for function 'dbFetch' for signature '"character"'
```

**Comment by krlmlr** [comment]
Thanks. Please use `dbFetch(rs, n = -1)` (and then `dbClearResult()`), or even simpler use `dbGetQuery()` instead of send + fetch + close.

**Comment by arecibo** [comment]
Many thanks. 
It was my big big mistake. 
I don't know why I made this mistake, and raised this issue. 

> Thanks. Please use `dbFetch(rs, n = -1)` (and then `dbClearResult()`), or even simpler use `dbGetQuery()` instead of send + fetch + close.

**Comment by krlmlr** [comment]
Thanks, don't worry. We now have something googleable for this error message, and your error description was very clear and made it easy to get to the source of the error.
