### ISSUE TITLE
`dbDataType()` not very useful for text

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/RMariaDB#279]
It returns `VARCHAR` with size of the longest text.

``` r
con <- DBI::dbConnect(
  RMariaDB::MariaDB(),
  dbname = "test"
)
DBI::dbDataType(con, "")
#> [1] "VARCHAR(1)"
DBI::dbDataType(con, "a")
#> [1] "VARCHAR(1)"
DBI::dbDataType(con, "ab")
#> [1] "VARCHAR(2)"
```

<sup>Created on 2022-08-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Thanks, sorry for being slow here.

What should `dbDataType()` be returning in this case? Character types have their tradeoffs on databases, we don't want to store all text columns as BLOBs by default.

What is your use case?

**Comment by krlmlr** [comment]
To solve this, we would need a custom class that knows about the maximum length of the strings. Out of scope here, sorry.
