### ISSUE TITLE
RMariaDB Failed to Connect with no Error message

### ISSUE THREAD

**Issue by KevinYie** [r-dbi/RMariaDB#280]
We have a MariaDB database running on an HPC cluster. There is no issues connecting using the MariaDB mysql API with the user. However, using the RMariaDB dbConnect function with the same information returns "Error: Failed to connect:" with no explanation. There is no entry in the mariadb.log for this attempt either. Please let me know if there is any more information you need! Thank you for your time and help! 

```r
library("RMariaDB")
tb2 <- dbConnect(drv = RMariaDB::MariaDB(), dbname="tacobell2", username="wue04", password="<removed>", host="db", port=33070)
```

**Comment by krlmlr** [comment]
Thanks, this fell through the cracks.

I'm sorry I couldn't help here. Were you able to resolve the issue?
