### ISSUE TITLE
TSLv1.3 bug

### ISSUE THREAD

**Issue by lukesingleton20** [r-dbi/RMariaDB#282]
There appears to be something bugged with TLSv1.3. My R code doesn't allow me to connect by using TLS certificates. I was able to connect from a Debian WSL2 VM on my Windows 11 machine without the SSL parameters to my MariaDB server (which is on my home server) via an unencrypted connection. 

I was also able to connect via SSL to the MariaDB server from the Debian WSL2 VM using the mysql command-line, so I'm positive I can connect to this database using SSL and using these exact certificates from my Windows 11/Debian VM machine. 

I have tried to execute the code below in both RStudio in Windows 11 Pro and in R-base on the Debian WSL2 VM, and get the same error from both, which suggests to me that its OS agnostic (baring any funny business with the way WSL2 works). 

Windows 11 is up-to-date and has TSLv1.3 enabled. The Debian VM is version 11. The MariaDB server is running on Ubuntu server 22.04.1 LTS. 

The error is:

Error: Failed to connect: SSL connection error: no cipher match. Error 0x80090331(SEC_E_ALGORITHM_MISMATCH)

```r
library(DBI)
library(pool)
library(RMariaDB)

pool <- dbPool(
  drv = RMariaDB::MariaDB(),
  dbname = "test",
  user = "user",
  host = "xx.xx.xx.xx",
  port = "3306",
  password = "xxxxxxxxxxxx",
  client.flag = CLIENT_SSL,
  ssl.key = "client-key.pem",
  ssl.cert = "client-cert.pem",
  ssl.ca = "ca-cert.pem",
  ssl.cipher = "TLSv1.3"
)
```
I have also tried removing client.flag, ssl.ca and ssl.cipher and they result in the same error. If I remove ssl.key or ssl.cert then I get a different error (that it cannot find a relevant PEM file). I should note that I haven't yet tried using a TSLv1.2 cipher to generate the certificates to see if that would work. I thought perhaps I should note it here to see if there was already a known issue.

**Comment by krlmlr** [comment]
Thanks. Do you see similar behavior with the command-line client?

**Comment by lukesingleton20** [comment]
From my Debian WSL2 VM using the mysql command-line I am able to connect:
![Screenshot 2022-09-30 074031](https://user-images.githubusercontent.com/111051636/193207994-3b635e6c-90e9-4561-b7ba-8c310319c60a.png)

Also from the Debian WSL2 VM using the R command-line, the same error as from RStudio on Windows 11:
![Screenshot 2022-09-30 075118](https://user-images.githubusercontent.com/111051636/193209729-6accea00-4b54-4f5c-8b14-11946ad7ad12.png)

Just to confirm the contents of /etc/mysql/mariadb.conf.d/50-mysql-clients.cnf on the Debian WSL2 VM:
![Screenshot 2022-09-30 075658](https://user-images.githubusercontent.com/111051636/193209805-8e933905-8700-46f1-a954-94cd67945e0c.png)

**Comment by krlmlr** [comment]
Thanks. The `cipher` argument is passed to `mysql_ssl_set()`, but that doesn't list possible ciphers. Are you sure about the `"TLSv1.3"` value? Can you please try `mysql ... --ssl-cipher=...` from the command line?

**Comment by krlmlr** [comment]
Thanks for the context, happy to hear that you could work around the issue.
