### ISSUE TITLE
dbWriteTable much slower in RMariaDB than ODBC

### ISSUE THREAD

**Issue by mbarneytu** [r-dbi/RMariaDB#290]
Creating a table of 8000 rows takes about 12 minutes:

```r
mariaConn <- dbConnect(
      RMariaDB::MariaDB(),
      host = config$server,
      dbname = config$database,
      user = config$uid,
      password = config$pwd
    )

system.time(dbWriteTable(mariaConn, "treering", as_tibble(datasets::treering)))
   user  system elapsed 
   0.52    0.74  706.51
```
The same operation using the MariaDB ODBC connector takes about 1 second:
```r
ODBCcon <- DBI::dbConnect(
  odbc::odbc(), 
  Driver = "MariaDB ODBC 3.1 Driver",
  Server = config$server,
  Database = config$database,
  UID = config$uid,
  PWD = config$pwd,
  timeout = 10
)

system.time(dbWriteTable(ODBCcon, "treering", as_tibble(datasets::treering)))
   user  system elapsed 
   0.03    0.00    1.02 
```

Unfortunately, the MariaDB ODBC connector is not available on shinyapps .io, so I can't use it.

**Comment by krlmlr** [comment]
Thanks. Can you please try `dbConnect(load_data_local_infile = TRUE)` ?

https://rmariadb.r-dbi.org/reference/dbconnect-mariadbdriver-method

**Comment by mbarneytu** [comment]
Thanks @krlmlr for your quick reply. So, when I set that flag, I get this error from dbWriteTable:
```r
Error: Error executing query: The used command is not allowed with this MariaDB version
```
My server (hosted at Lithium Hosting) is version 10.3.36.
Rather than being a version problem, it appears that the server is just not configured to allow the LOAD DATA LOCAL INFILE command (attempting that command directly from an SQL client returns the same error). The server has the "[local_infile](https://mariadb.com/kb/en/server-system-variables/#local_infile)" system variable turned off. Since it's shared hosting, they don't seem to be willing to turn it on.

Let me know if you have other suggestions, and thanks again.

**Comment by krlmlr** [comment]
Thanks. Unfortunately, LOAD DATA LOCAL INFILE has this limitation. Does the service provider offer bulk uploading? You could try composing a `INSERT INTO ... VALUES ...` query, I believe `sqlAppendTable()` does just that.

Closing, there's not much we can do here.

**Comment by mbarneytu** [comment]
@krlmlr sqlAppendTable() worked beautifully, using odbc() with the MySQL connector! Thanks again.
