### ISSUE TITLE
RMariaDB 1.2.2 with MariaDB under macOS Ventura 13.4 returns wrong values

### ISSUE THREAD

**Issue by SwissMontainsBear** [r-dbi/RMariaDB#298]
I have a database (MariaDB 11.0.2) loaded with financial market values.
SQL request works like this:
```
+--------+------------+-----------+-----------+-----------+-----------+--------+----------+
| ticker | date       | open      | high      | low       | close     | volume | adjclose |
+--------+------------+-----------+-----------+-----------+-----------+--------+----------+
| SPY    | 1980-01-02 | 15.255781 | 15.255781 | 15.255781 | 15.255781 | 0      | 5.175430 |
| SPY    | 1980-01-03 | 15.181311 | 15.181311 | 15.181311 | 15.181311 | 0      | 5.150164 |
| SPY    | 1980-01-04 | 15.372806 | 15.372806 | 15.372806 | 15.372806 | 0      | 5.215130 |
| SPY    | 1980-01-07 | 15.415361 | 15.415361 | 15.415361 | 15.415361 | 0      | 5.229562 |
| SPY    | 1980-01-08 | 15.723881 | 15.723881 | 15.723881 | 15.723881 | 0      | 5.334226 |
| SPY    | 1980-01-09 | 15.745158 | 15.745158 | 15.745158 | 15.745158 | 0      | 5.341450 |
+--------+------------+-----------+-----------+-----------+-----------+--------+----------+

```

Updating RMariaDB to 1.2.2 causes simple SQL request to return erroneous values.
---
With RMariaDB 1.2.2: the following request is returning strange values...
```
> require('RMariaDB')
> con <- dbConnect(MariaDB(),group='my-db')
> res = dbSendQuery(con,'select * from dailydata where ticker = "SPY";')
> fr <- dbFetch(res, n=-1)
> head(fr)
 ticker date     open     high      low    close    volume adjclose
1      0    0 15.25578 15.25578 15.25578 15.25578 889729025   175430
2      0    0 15.18131 15.18131 15.18131 15.18131 889729025   150164
3      0    0 15.37281 15.37281 15.37281 15.37281 889729025   215130
4      0    0 15.41536 15.41536 15.41536 15.41536 889729025   229562
5      0    0 15.72388 15.72388 15.72388 15.72388 889729025   334226
6      0    0 15.74516 15.74516 15.74516 15.74516 889729025   341450

```
Reverting RMariaDB to 1.2.1 with the same version of MariaDB produces correct values
```
> require('RMariaDB')
> con <- dbConnect(MariaDB(),group='my-db')
> res = dbSendQuery(con,'select * from dailydata where ticker = "SPY";')
> fr <- dbFetch(res, n=-1)
> head(fr)
  ticker       date     open     high      low    close volume adjclose
1    SPY 1980-01-02 15.25578 15.25578 15.25578 15.25578      0 5.175430
2    SPY 1980-01-03 15.18131 15.18131 15.18131 15.18131      0 5.150164
3    SPY 1980-01-04 15.37281 15.37281 15.37281 15.37281      0 5.215130
4    SPY 1980-01-07 15.41536 15.41536 15.41536 15.41536      0 5.229562
5    SPY 1980-01-08 15.72388 15.72388 15.72388 15.72388      0 5.334226
6    SPY 1980-01-09 15.74516 15.74516 15.74516 15.74516      0 5.341450

```
Rem: 

- this does not happen under Linux with Ver 15.1 Distrib 10.5.20-MariaDB and RMariaDB 1.2.2
- this does not happen either under macOS with MySQL community server 8.0.31 and RMariaDB 1.2.2
- I tried downgrading to last long term release of MariaDB (10.11) and this did not help and behavior remained same: works with 1.2.1 and does not work with 1.2.2

Any clue if I am doing something wrong ?

**Comment by krlmlr** [comment]
Thanks, weird. Are you comfortable compiling RMariaDB from source? Does the error still occur there?

**Comment by SwissMontainsBear** [comment]
Thanks for your help.
This is weird really.
When installing for source, the behaviour is OK, except I receive an error (Error: No database selected [1046]) which implies that RMariaDB cannot read my-db configuration from .my.cnf file.

```
other attached packages:
[1] RMariaDB_1.2.2.9008

loaded via a namespace (and not attached):
 [1] bit_4.0.5        compiler_4.3.0   generics_0.1.3   cli_3.6.1       
 [5] hms_1.1.3        tools_4.3.0      DBI_1.1.3        bit64_4.0.5     
 [9] lubridate_1.9.2  vctrs_0.6.2      timechange_0.2.0 lifecycle_1.0.3 
[13] pkgconfig_2.0.3  rlang_1.1.1     
> con <- dbConnect(MariaDB(),group='my-db')
> res = dbSendQuery(con,'select * from dailydata where ticker = "SPY";')
Error: No database selected [1046]
> res <- dbSendQuery(con,'use stocks')
> res = dbSendQuery(con,'select * from dailydata where ticker = "SPY";')
Warning message:
Cancelling previous query 
> fr <- dbFetch(res, n=-1)
> head(fr)
  ticker       date     open     high      low    close volume adjclose
1    SPY 1980-01-02 15.25578 15.25578 15.25578 15.25578      0 5.175430
2    SPY 1980-01-03 15.18131 15.18131 15.18131 15.18131      0 5.150164
3    SPY 1980-01-04 15.37281 15.37281 15.37281 15.37281      0 5.215130
4    SPY 1980-01-07 15.41536 15.41536 15.41536 15.41536      0 5.229562
5    SPY 1980-01-08 15.72388 15.72388 15.72388 15.72388      0 5.334226
6    SPY 1980-01-09 15.74516 15.74516 15.74516 15.74516      0 5.341450
```

The rest of the query is returned normally, after specifying the database.
Any clue how I can force RMariaDB to get the database name from .my.cnf to avoid rewriting my code ?

**Comment by krlmlr** [comment]
I remember the RMariaDB drivers specifically ignored auth data in `.my.cnf`, there might well be no way around this. Can you compile against MySQL drivers? Try setting the `RMARIADB_FORCE_MYSQLCONFIG` environment variable to a nonempty string before rebuilding from source.

**Comment by SwissMontainsBear** [comment]
Thanks again for your help. Recompiling with this environment variable did not help. What is strange is that the user name and password are retrieved and not the database name. 
But no worries. I do not want to abuse your time and support.
It's not such a big trouble to add the dbExecute statement in my code. 
I will close this case if you agree.

**Comment by SwissMontainsBear** [comment]
Correction: this issue with my-db config arose from pulling the code from github via 
`devtools::install_github("r-dbi/RMariaDB")`
When downloading the source package from CRAN, I do not have this issue.
The strange behaviour is also solved. 
So case closed for me.
Thanks again for your support :-)
