### ISSUE TITLE
Database appears empty in RStudio

### ISSUE THREAD

**Issue by ryan-hdez** [r-dbi/RMariaDB#302]
Hello,

I’m running into an interesting situation where I can connect to my database, but the database appears empty. 

I first ran **dbCanConnect**, which returns TRUE. I then connected using **dbConnect**, and just to check my database, I ran the following query:
```r
dbFetch(dbSendQuery(conn, "SHOW TABLES;"))
```
I’ve verified using MariaDB Server (on Mac) that my database isn’t empty. It contains 15 tables, but the query above displays a column of 15 zeroes in RStudio, like so:
```r
 Tables_in_db
1                        0
2                        0
3                        0
4                        0
5                        0
6                        0
7                        0
8                        0
9                        0
10                       0
11                       0
12                       0
13                       0
14                       0
15                       0
```
Since I know the actual names of the tables, I tried accessing one using 
```r
dbFetch(dbSendQuery(conn, "SELECT * FROM table;”))
```
Again, the structure was what I expected (same # of rows and same columns), but the table was empty.

Any idea why this might be happening? Thanks!

~~
@daniellebraun

**Comment by krlmlr** [comment]
Thanks. Can you please try installing RMariaDB from source?
