### ISSUE TITLE
RMariaDB() not working

### ISSUE THREAD

**Issue by kwakuduahc1** [r-dbi/RMariaDB#314]
The `group` argument for the `RMariaDB()` functions seems to work no more. 

I have tried on 2 different Ubuntu 22 servers and it does not seem to read from the `.my.cnf` file located in the user directory
 It works as expected if I provide a username and a password. The error seems it tries to connect with the username I used to log into RStudio despite the username for MySQL being different.

It worked months ago and I cannot recollected the exact time it stopped working.

``` r
DBI::dbConnect(RMariaDB::MariaDB(), group = "rs-dbi")
#> Error: Failed to connect: Access denied for user 'username'@'localhost' (using password: NO)
```

Where *username* is the ID used to access the RStudio Server

<sup>Created on 2023-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Where the __rs_dbi__ file is located in __~/.my.cnf__ and reads** 

```
[rs-dbi]
database="my_db"
user="my_username"
password="my_password"
```

**Comment by krlmlr** [comment]
Thanks. Is this fixed by https://github.com/r-dbi/RMariaDB/pull/306, already on the main branch?

**Comment by kwakuduahc1** [comment]
No, I am not on the main branch, I installed from CRAN.

Then again, is the parameter name changing from `group` to `groups`?

Thanks.

**Comment by krlmlr** [comment]
AFAICT it's been `groups` for a while now, you can use `group` thanks to R's partial matching.

**Comment by krlmlr** [comment]
`group` and `groups` will both work in the upcoming CRAN version, and should already work even with the current version. Can you confirm?

**Comment by kwakuduahc1** [comment]
On version _1.3..1_, both params work.
