### ISSUE TITLE
Explain leads to `bad value` error

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/RMariaDB#316]
Found when running the dbplyr tests. This was introduced with v1.3.0 and still happens in the dev version.

**Edit**: Sorry, didn't check the reprex again when running it the second time.
The issue only seems to appear when I connect to an SQLite db before 😕 

``` r
con_sqlite <- DBI::dbConnect(
  RSQLite::SQLite(), ":memory:"
)
con <- DBI::dbConnect(
  RMariaDB::MariaDB(),
  dbname = "test",
  host = "localhost",
  username = Sys.getenv("USER")
)

DBI::dbWriteTable(con, "test", data.frame(x = 1:3))
DBI::dbGetQuery(
  con,
  "EXPLAIN SELECT `test`.*, `x` + 1.0 AS `y` FROM `test`"
)
#> Error in result_fetch(res@ptr, n = n): bad value
```

<sup>Created on 2023-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Thanks. What is the expected behavior here?

**Comment by mgirlich** [comment]
Argh, sorry, I ran the reprex again and didn't check that it didn't contain the issue anymore. This only seems to happen when connection to SQLite before. Interesting.

**Comment by krlmlr** [comment]
Works for me:

``` r
pkgload::load_all()
#> ℹ Loading RMariaDB
#> ! Skipping missing files: '/root/workspace/R/names.R'

con_sqlite <- DBI::dbConnect(
  RSQLite::SQLite(), ":memory:"
)
con <- DBI::dbConnect(
  RMariaDB::MariaDB()
)

DBI::dbWriteTable(con, "test", data.frame(x = 1:3), overwrite = TRUE)
DBI::dbGetQuery(
  con,
  "EXPLAIN SELECT `test`.*, `x` + 1.0 AS `y` FROM `test`"
)
#>   id select_type table type possible_keys  key key_len  ref rows Extra
#> 1  1      SIMPLE  test  ALL          <NA> <NA>    <NA> <NA>    3
```

<sup>Created on 2024-04-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Can you please double-check in your setup?

**Comment by mgirlich** [comment]
Seems to be fixed now 👍
