### ISSUE TITLE
Turn off column name mangling?

### ISSUE THREAD

**Issue by hpages** [r-dbi/RMariaDB#321]
`dbGetQuery()` and other `dbFetch`-based operations mangle the column names of the result if some of them are duplicated. This is done in `dbFetch()` by calling `RMariaDB:::set_tidy_names()` on the result.

How about making this mangling optional via a global option or an additional argument to `dbGetQuery`/`dbFetch`?

Problem with this mangling is that:
- it's inconsistent with the command line `mysql`/`mariadb` clients,
- it's not always desirable (I would even argue that it's almost never desirable),
- there's not reliable way to restore the real column names,
- it's inconsistent with **RSQLite** and **RMySQL**, two other members of the **DBI** family.

See https://github.com/r-dbi/RSQLite/issues/308 for a previous discussion of column name mangling.

Thanks,
H.

**Comment by krlmlr** [comment]
Thanks, good catch. We agreed previously that name mangling isn't DBI's responsibility: https://github.com/r-dbi/DBItest/pull/247.

**Comment by krlmlr** [comment]
Hm... we had similar code in RSQLite, https://github.com/r-dbi/RSQLite/pull/503/files. Anyway, this will be gone with the next CRAN release.

**Comment by hpages** [comment]
Thanks @krlmlr !
