### ISSUE TITLE
RMariaDB always fail to connect to a database

### ISSUE THREAD

**Issue by mgerault** [r-dbi/RMariaDB#334]
I would like to use RMariaDB to create an SQL database from an .sql file.
I use a virtual machine on Windows which operates under Ubuntu 20.04.6. mysql and mysql-server are both version 8.0. I installed succesfully the MariaDB Connector with 
```
sudo apt-get install -y libmariadb-dev
```

R version is 4.4 and package RMariaDB is version 1.3.1 and DBI is version 1.2.2. 

My my.cnf file is located in /etc/mysql/ and contains the following:
```
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

[mysqld]
datadir = /home/user/

[mariadb]
datadir = /home/user/

[rs-dbi]
database="test"
user="root"
password=""
```
And the 'test.db' file is located in '/home/user/'

However, whenever I run in R
```
library(DBI)
con <- dbConnect(RMariaDB::MariaDB())
```
I always get 
```
Error : Failed to connect: Unknown database 'test'
```

No mattter the option I set or tried, even adding other options in ~/.my.cnf I wasn't able to connect any object using RMariaDB.

Do I miss something ? A step I didn't do ?

Thanks in advance for your help.

**Comment by krlmlr** [comment]
Thanks. What was the resolution? How can we document this better?

**Comment by mgerault** [comment]
I had a problem with my mariadb installation. I reinstall everything and it worked. I just had to create a database named 'test' with mariadb as it wasn't there by default.
