### ISSUE TITLE
Translation for %/% unavailable

### ISSUE THREAD

**Issue by jonas-endter-optimax-energy** [r-dbi/RMariaDB#342]
There is no translation provided for integer division even though [MySQL supports it](https://dev.mysql.com/doc/refman/8.4/en/arithmetic-functions.html#operator_div).

```r
dbplyr::translate_sql(x%/%5, con = db_con)
```
![image](https://github.com/user-attachments/assets/88f2e240-8156-4dce-8f91-7a557800ea09)

**Comment by jonas-endter-optimax-energy** [comment]
https://mariadb.com/kb/en/div/
this seems to be supported in MariaDB as well

**Comment by jonas-endter-optimax-energy** [comment]
https://github.com/tidyverse/dbplyr/issues/108#issuecomment-696941162
hmm ig it's not happening there either

**Comment by krlmlr** [comment]
Thanks. You can use `sql()` inside `mutate()` for greater control over the generated SQL, as in

```r
db_tbl %>%
  mutate(y = sql("x / 5"))
```

It seems that not supporting `%>%` was a deliberate decision.
