### ISSUE TITLE
dbQuoteLiteral with MySQL 8.0

### ISSUE THREAD

**Issue by jjaeschke** [r-dbi/RMariaDB#352]
DBI Version 1.2.3 changed the format returned by `dbQuoteLiteral()` for `POSIXct` values from `%Y%m%d%H%M%S` to `%Y-%m-%d %H-%M-%S%z`. This breaks support for MySQL 8.0, as the string is no longer recognized as a valid DATETIME string due to the added timezone info. 

It might be an issue with MySQL 8 or MySQL in general, but since I don't have a server of those other versions to check against, I can't tell for certain.

Since this seems to be an issue specific to MySQL 8.0, I'm filing it here, rather than with the DBI package itself. If this is wrong, please advise and I'll file it there, instead.

**Comment by krlmlr** [comment]
Thanks, that's too bad.

There's a new-ish `mysql = NULL` argument to our `dbConnect()` . Can we leverage that to quote literals differently depending on the database we connect to?

**Comment by jjaeschke** [comment]
`dbConnect()` does return an object of the class `MySQLConnection` if `mysql` is `TRUE`.

Maybe we could create a method for `dbQuoteLiteral()` for that class that overrides the behavior for quoting Datetime objects and refers to the more generic method for everything else?

**Comment by jjaeschke** [comment]
I've tried implementing this in a barebones PR. Let me know if this needs some more work.

**Comment by krlmlr** [comment]
Merged now, thanks again!
