### ISSUE TITLE
Implement RStudio Connection Contract

### ISSUE THREAD

**Issue by edgararuiz** [r-dbi/RMariaDB#55]
The Connection Contract integrates the RStudio IDE with the database connection. Here is the link with the details: https://rstudio.github.io/rstudio-extensions/connections-contract.html

**Comment by krlmlr** [comment]
Rather than implementing the contract in each DBI backend, how about implementing it in DBI itself? Something like

```r
setGeneric("dbConnect",
  def = function(drv, ...) {
    con <- standardGeneric("dbConnect")
    register_con_with_rstudio(con)
    con
  },
  valueClass = "DBIConnection"
)
```

instead of the current implementation:

```r
setGeneric("dbConnect",
  def = function(drv, ...) standardGeneric("dbConnect"),
  valueClass = "DBIConnection"
)
```

? The same for `dbDisconnect()`. To catch disconnects that happen through garbage collection, we could register a finalizer on the external pointer that lives in the connection.

@jimhester @javierluraschi @edgararuiz: Thoughts?

**Comment by edgararuiz** [comment]
Yes! That's what I would rather have.  It centralizes updates and it will
give any new an existing DBI compliant immediate integration w the IDE!

On Sep 23, 2017 12:40 PM, "Kirill Müller" <notifications@github.com> wrote:

Rather than implementing the contract in each DBI backend, how about
implementing it in DBI itself? Something like

setGeneric("dbConnect",
  def = function(drv, ...) {
    con <- standardGeneric("dbConnect")
    register_con_with_rstudio(con)
    con
  },
  valueClass = "DBIConnection"
)

instead of the current implementation:

setGeneric("dbConnect",
  def = function(drv, ...) standardGeneric("dbConnect"),
  valueClass = "DBIConnection"
)

? The same for dbDisconnect(). To catch disconnects that happen through
garbage collection, we could register a finalizer on the external pointer
that lives in the connection.

@jimhester <https://github.com/jimhester> @javierluraschi
<https://github.com/javierluraschi> @edgararuiz
<https://github.com/edgararuiz>: Thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rstats-db/RMariaDB/issues/55#issuecomment-331656791>,
or mute the thread

**Comment by russellpierce** [comment]
What dependencies (if any) will this add to DBI or RMariaDB?

**Comment by edgararuiz** [comment]
None that I can see, I checked the instructions (http://db.rstudio.com/advanced/contract) and `odbc`'s implementation of the Contract: https://github.com/rstats-db/odbc/blob/5acc55350e0664002d6281f4659c089911fbd7c3/R/Viewer.R

**Comment by jimhester** [comment]
I would prefer having this in DBI as well. @jmcphers would probably be the person to consult about what changes were necessary in DBI to get this working for all compliant backends.

**Comment by nwstephens** [comment]
I would love to see the connection contract implemented in DBI. What's the status on this? @krlmlr

**Comment by krlmlr** [comment]
Will look at it in December. In the meantime, happy to review ideas/PRs in the DBI package ;-)

**Comment by jtelleriar** [comment]
Thank you to you for your great work with RMariaDB.

Juan

El 14/11/2017 8:54 a. m., "Kirill Müller" <notifications@github.com>
escribió:

Will look at it in December. In the meantime, happy to review ideas/PRs in
the DBI package ;-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/r-dbi/RMariaDB/issues/55#issuecomment-344174128>, or mute
the thread

**Comment by edgararuiz** [comment]
@krlmlr - I started working on the contract, and what I have so far works well for DBs that have no schemata. For databases with more than one schema,  `dbListTables()` does not provide enough data to create a tree that the user can drill into (db-schema-table/view), and there's no `dbListSchemas()` command available.  We could implement something w/o displaying the schema, but that will mean that the user will not know which schema to use when the try to call it via `dbGetQuery()` for example.  Thoughts?

cc @nwstephens

**Comment by krlmlr** [comment]
@edgararuiz: Schema support is pending (r-dbi/DBI#24), I'll tackle it later in December. Would you mind sharing your current implementation so that we can discuss there?

**Comment by edgararuiz** [comment]
@krlmlr - Sounds good, here's the link to the Gist: https://gist.github.com/edgararuiz/0533b3daf70a41b70acd75c1e6a2b7a3 

It is essentially a simplified version of the `odbc`'s package contract: https://github.com/r-dbi/odbc/blob/master/R/Viewer.R

**Comment by edgararuiz** [comment]
@krlmlr - as an aside, what are the plans for other DB elements, like enumerating databases inside a server?  Ideally, we should be able to list databases inside a server, schemata inside a database, tables/views inside a schema.  Also, are the plans to add more metadata to `dbListTables()` so we can see differentiate between tables and views?

**Comment by krlmlr** [comment]
@edgararuiz: We should be able to support most of what you're suggesting, please see #24 for details.

Closing in favor of https://github.com/r-dbi/DBI/issues/211.
