### ISSUE TITLE
will not read .my.cnf on Windows 10

### ISSUE THREAD

**Issue by vishalrunner** [r-dbi/RMariaDB#74]
I am using RStudio on  Windows 10.  I have a mariadb remotely hosted on AWS. 
I can connect to it using
con <- dbConnect(RMariaDB::MariaDB(), host = "xyzabc1234.us-east-1.rds.amazonaws.com",
                 user = "master", password = "password", dbname = "test")

Here's the .my.cnf file
[test]
database=xyzabc1234.us-east-1.rds.amazonaws.com
user=master
password=password
port=3306

I experimented different permutations and stored it in 3 different places
c:\
c:\Users\my-account\
[current working directory]

I always get this error
> mariadbHasDefault()
Could not initialise default MariaDB database. If MariaDB is running
check that you have a ~/.my.cnf file that contains a [rs-dbi] section
describing how to connect to a test database.
[1] FALSE

I tried using the default-files options
>settingsfile <- "C:/Users/myname/Documents/code/test/"
>con <- dbConnect(RMariaDB::MariaDB(), default.file = settingsfile, groups="test" )
Error in connection_create(host, username, password, dbname, as.integer(port),  : 
  Failed to connect: Can't connect to MySQL server on 'localhost' (0)

The error message indicates that it couldnt find my settings file. I hate to have my credentials embedded in my code.

**Comment by krlmlr** [comment]
Thanks. Maybe you need `.mylogin.cnf`? RMariaDB doesn't do anything special, can you please double-check the documentation at https://mariadb.com/kb/en/library/configuring-mariadb-with-mycnf/?

**Comment by foundinblank** [comment]
This is not exactly related, but it may help others who have similar issues with .my.cnf - there can't be spaces around `=`.  Took me too long to figure that out.  🙁  

This will not work:
```
[test]
user = test
pass = **** 
```

This will:
```
[test]
user=test
pass=**** 
```

Also, if you want to specify the database in `.my.cnf`, use `database=` not `dbname=`. A bit confusing because `MariaDB()` uses `dbname`. 

**Anyway, keep up the good work, RMariaDB team! 👍 💯 This is way easier to set up than ODBC.**

**Comment by gregforcey** [comment]
I had this same issue and what worked for me was to rename `.my.cnf` without the leading dot `my.cnf`

Also I had to put the file in my `C:\` directory. Placing it in my user folder or R working directory did not work.

The name that is in brackets at the beginning must match the group argument in the `dbConnect` function.  Here is what my complete `my.cnf file looks like:

```
[group]
host=host
database=db
user=user
password=pass
port=3306
```

**Comment by krlmlr** [comment]
Thanks for the feedback. I'll close this for now, please open a new issue if problems persist.
