### ISSUE TITLE
.onLoad needs to return TRUE

### ISSUE THREAD

**Issue by phaverty** [r-dbi/RMariaDB#75]
requireNamespace("RMariaDB") does not return TRUE, rather it returns NULL

requireNamespace("RMariaDB") || stop("Failed to load RMariaDB.") should work.

I believe this is why devtools::document() fails on packages that require RMariaDB.
Please see https://stackoverflow.com/questions/33428055/dependency-package-package-name-not-available

**Comment by krlmlr** [comment]
Thanks. It works for me on Linux and with current R. What OS and R version are you using?

``` r
(requireNamespace("RMariaDB"))
#> Loading required namespace: RMariaDB
#> [1] TRUE
```

Created on 2017-12-18 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by phaverty** [comment]
This used to fail with R 3.4.0 on linux.
With R 3.4.3 (and RMariaDB 1.0.4), on linux, this now works fine. I guess there isn't anything to do. Thanks for taking a look.

**Comment by krlmlr** [comment]
Thanks. We aim at compatibility for older versions of R, can you confirm on which R versions returning `FALSE` in `.onLoad()` fails? Are R 3.3.x or R 3.2.x affected?

**Comment by phaverty** [comment]
On OSX 10.12.6, R 3.3.3, RMariaDB 1.0.4, requireNamespace("RMariaDB")
returns TRUE.
On linux RedHat 6, R 3.3.3, RMariaDB 1.0.4, requireNamespace("RMariaDB")
returns TRUE.

I don't have a copy of R 3.2 around.  Hmm, I guess everything is OK now?

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by krlmlr** [comment]
The StackOverflow link mentions that throwing an error in `.onLoad()` (correctly) leads to `requireNamespace()` returning `FALSE`. Let's leave this for now, please open a new issue if problems persist.
