### ISSUE TITLE
SSL Connection Error: Certificate Verify Failed

### ISSUE THREAD

**Issue by tylerb626** [r-dbi/RMariaDB#85]
I am currently running into an issue where I can connect to a database on the first attempt but after disconnecting and attempting to establish a new connection I am getting the following error:

 "Failed to connect: SSL connection error: certificate verify failed."

The only way to fix this issue is to close RStudio (terminate the R session) and reopen it. After restarting RStudio the database will connect on the first try but then fall into the same error. The code I'm using:

library(RMariaDB)
con <-dbConnect(RMariaDB::MariaDB(), dbname = ***, host = ***, port = ***, default.file = ***, group = ***)

I am passing in the username, password, and path to a ca file in the cnf file. I was previously running this on a Windows 10 laptop and never ran into this issue. I could connect, disconnect, and reconnect as many times as needed.  I am now using OSX 10.13.3 (High Sierra) and am getting this error. 

My R session info: 

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.0-4

loaded via a namespace (and not attached):
 [1] bit_1.1-12      compiler_3.4.3  hms_0.4.1       DBI_0.7         tools_3.4.3     yaml_2.1.16     Rcpp_0.12.15    bit64_0.9-7     pkgconfig_2.0.1 rlang_0.1.6   

This does not appear to be an RStudio issue, as it also happens when running the code straight from an R terminal. 

Thanks,
Tyler

**Comment by craigmaxey33** [comment]
I'm having the same issue.  

R version: 3.4.3
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running Under: macOS High Sierra 10.13.3

Is this an OSX issue? 

Thanks.
