### ISSUE TITLE
Window functions and MariaDB

### ISSUE THREAD

**Issue by norbusan** [r-dbi/RMariaDB#89]
Dear all,
I am not sure whether this is the correct place, but playing around with RMariaDB and trying to convert some statements into sql with `show_query()` I often get an error from dplyr stating that `... does not support window functions`. I am running MariaDB 10.2, the current stable, which *should* support window functions, at least that is what they state. The query I am sending of is
```
  BW <- somedata_db %>%
    group_by(key1) %>%
    filter(key2 == max(key2)) %>%
    summarise(val=max(key3))
```
Appending to this a `%>% show_query()` always ends in the "does not support" error.

Thanks a lot

Norbert

**Comment by krlmlr** [comment]
Thanks. This seems to be a *dbplyr* problem. This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
