### ISSUE TITLE
R session crash when using dbWriteTable (V2)

### ISSUE THREAD

**Issue by AdrienMtgn** [r-dbi/RMariaDB#95]
Don't know if I am supposed to open a new issue for this one as it is exactly the same as #79 but with another kind of boundary.

R session crashes when I write in MySQL db a "negative" Date.

```
conn<-dbConnect(MariaDB(),
group = "dbname",
default.file=Sys.getenv("R_SQL_CONN_FILE"))

dbWriteTable(conn,"test",data.frame(test=Sys.Date()),overwrite=T) #OK
dbWriteTable(conn,"test",data.frame(test=as.Date("1900-01-01")),overwrite=T) #Crash

dbWriteTable(conn,"test",data.frame(test=as.Date("1970-01-01")),overwrite=T) #OK
dbWriteTable(conn,"test",data.frame(test=as.Date("1969-12-31")),overwrite=T) #Crash
```

Session info : 
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7600)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.0.5

loaded via a namespace (and not attached):
[1] bit_1.1-12      compiler_3.4.3  hms_0.4.2       DBI_1.0.0       tools_3.4.3     Rcpp_0.12.16    bit64_0.9-7     pkgconfig_2.0.1
[9] rlang_0.2.0 `
```

log Files : 
[rdesktop.log](https://github.com/r-dbi/RMariaDB/files/1975052/rdesktop.log)
[rsession-adrien.montagnon.log](https://github.com/r-dbi/RMariaDB/files/1975053/rsession-adrien.montagnon.log)

Windows dump file :
[rsession.exe.18808.zip](https://github.com/r-dbi/RMariaDB/files/1975138/rsession.exe.18808.zip)

Edit : Just tryed latest dev version and it crashed the same way. The dump file was created this way.

**Comment by msissons** [comment]
I can confirm I'm also getting this behaviour in Windows using the latest dev version. This does not occur in the CRAN version (1.0.6) running on Linux. 

I think it may be related to the MariaDB C connector for Windows - version 2.3.6 changelog lists a fix for negative dates (see Revision #fb100c8 @ [https://mariadb.com/kb/en/library/mariadb-connector-c-236-changelog/](https://mariadb.com/kb/en/library/mariadb-connector-c-236-changelog/))

sessionInfo():
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.0.6

loaded via a namespace (and not attached):
[1] bit_1.1-12      compiler_3.5.0  hms_0.4.2       DBI_1.0.0      
[5] Rcpp_0.12.18    bit64_0.9-7     pkgconfig_2.0.1 rlang_0.2.1    

```

**Comment by jtelleriar** [comment]
Open please an issue into MariaDB's JIRA:

>
https://jira.mariadb.org/projects/MDEV/issues/MDEV-16870?filter=allopenissues

Specifying Connector/C

My only doubt is whether if RMariaDB uses MySQL or MariaDB Connector/C.

I think uses the one of MySQL.

**Comment by msissons** [comment]
Sorry, I didn't word that very well. I think that the issue has already been fixed by MariaDB, however the version of libmariadbclient library for Windows currently used by RMariaDB on the github repo (3.2.5) predates this fix. I suspect that updating to the 3.2.6 version may fix this issue.

**Comment by jtelleriar** [comment]
Solved then. Issue can be closed ;) Just update from CRAN.

>

**Comment by krlmlr** [comment]
@jeroen: Could you please provide libmariadbclient >= 3.2.6 for Windows?

**Comment by AtharKharal** [comment]
Same problem here with dbWriteTable()

**Comment by krlmlr** [comment]
This should be fixed with d84f5fa (thanks Jeroen!). Can you please try with the latest dev version?

**Comment by jeroen** [comment]
I see appveyor is failing tests on windows (it was already before this update), that worries me. On Win64 it just fails a test, but on Win32 it seems to crash?

**Comment by krlmlr** [comment]
On AppVeyor, I see one job testing both x64 and i386, but I don't see the crash. Could you please point me to the line in the log?

https://ci.appveyor.com/project/r-dbi/rmariadb/builds/21294371

**Comment by jeroen** [comment]
Can you try fixing the unit test, to see if the 32 problem goes away too?

**Comment by krlmlr** [comment]
Seeing test failures on my local install for both 32- and 64-bit architectures.

**Comment by jeroen** [comment]
Seeing the same test failure on MacOS too.

**Comment by krlmlr** [comment]
Closing in favor of 117, let's continue discussion there.
