### ISSUE TITLE
Good to have spatial object loading support

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [r-dbi/RMariaDB#96]
Hello all , Thanks for the great work. 

It will be great if we can add support for loading shape file to MySQL from R. I think, if we extend dbWriteTable method to handle spatial objects like spatial points, polygons and multi polygons, we can make use of that.  I am getting this error currently, 

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"MySQLConnection", "character", "SpatialPolygonsDataFrame"’
```

Thanks in advance.

**Comment by krlmlr** [comment]
Thanks. Your code seems to use _RMySQL_. Could you try converting to `sf` first?

**Comment by Jeeva-Ganesan** [comment]
Does that mean it is supported in RMariaDB if i use sf ?

**Comment by krlmlr** [comment]
There's a slim chance that this just works, perhaps you need to convert to WKT first. (_sf_ stores geometries in a list column, these are supported by _RMariaDB_.) I don't have access to a spatial MariaDB, but I'm curious if it works.
