### ISSUE TITLE
RMariaDB installation on CentOS7 using MariaDB 10.2/10.3 yum repos causes code to fail

### ISSUE THREAD

**Issue by wccropper** [r-dbi/RMariaDB#97]
The build of RMariaDB with CentOS 7 base mariadb packages (5.5) works. The shiny app works. We want to use the latest MariaDB client. Installation of the client/shared/common/compat packages from the 10.2.x or 10.3.x repos, RMariaDB builds, but the shiny app fails with the following:

Warning: Error in result_fetch: Error fetching buffer:
  92: <Anonymous>
Warning: Error in UseMethod: no applicable method for 'tbl_vars' applied to an object of class "NULL"
  113: tbl_vars
  111: inner_join.tbl_df
  109: <reactive:change_table> [/srv/shiny-server/app1/server.R#129]
   93: change_table
   92: renderUI [/srv/shiny-server/app1/server.R#158]
   91: func
   78: origRenderFunc
   77: output$main_tab
    1: shiny::runApp
Warning: Error in UseMethod: no applicable method for 'tbl_vars' applied to an object of class "NULL"
  95: <Anonymous>
Warning: Error in UseMethod: no applicable method for 'tbl_vars' applied to an object of class "NULL"
  95: <Anonymous>
Warning in (function (e)  : You have a leaked pooled object.
Warning: call dbDisconnect() when finished working with a connection

The compat package is a dependency of the client package. This installs the mysql lib/include and is used instead of the MariaDB lib/include but he RMariaDB install. I've also tried compiling the connector-c rpm but it conflicts with everything form the 10.2/10.3 repos.

The outcome I would like is a working MariaDB 10.3.x client, with latest connector-c, and the latest RMariaDB. How can this be accomplished?

**Comment by krlmlr** [comment]
Thanks. Are you still experiencing these problems? What happens when you access the database outside of your Shiny app?

**Comment by pablorocka** [comment]
I had issues with MariaDB 10.3.x client, and this worked for me:
https://github.com/r-dbi/RMariaDB/issues/69#issuecomment-353458710
But I see that the pull request got rejected because of compatibility with MySQL.

**Comment by krlmlr** [comment]
@pablorocka: Thanks. Could you please describe the problems you were seeing in a new issue? We could consider implementing #81 in a way that is compatible with MySQL.
