### ISSUE TITLE
DECIMAL handling

### ISSUE THREAD

**Issue by nbenn** [r-dbi/RMariaDB#98]
It might make more sense to return DECIMAL columns as character vectors and not as as numeric.

Current mapping:
https://github.com/r-dbi/RMariaDB/blob/720b88933cb92b4995df4bad747e2bc6f8ab3278/src/MariaTypes.cpp#L19-L23

For some there might issues when converting exact numeric values to an approximate representation.

See also (from [here](https://dev.mysql.com/doc/refman/5.6/en/c-api-prepared-statement-type-conversions.html))

> MySQL returns DECIMAL values as the string representation of the original server-side value, which is why the corresponding C type is char[]. For example, 12.345 is returned to the client as '12.345'. If you specify MYSQL_TYPE_NEWDECIMAL and bind a string buffer to the MYSQL_BIND structure, mysql_stmt_fetch() stores the value in the buffer as a string without conversion. If instead you specify a numeric variable and type code, mysql_stmt_fetch() converts the string-format DECIMAL value to numeric form.

**Comment by krlmlr** [comment]
Thanks. This looks like a sufficiently rare edge case (given that in most cases the user will need to process the values in R anyway). This problem could be worked around by coercing to character on the server.

Closing in favor of the more general https://github.com/r-dbi/DBI/issues/203.
