### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by smartsurrounding** [r-dbi/RMariaDB#99]
I write few Rscripts to make a db connection and check if a table exists.
There's a weird issue that when i run the Rscripts line by line,
I first run dbConnect() and dbExistsTable(), it returns TRUE;
after 10~20s, i run dbExistsTable() again, but it returns FALSE.

Is there any auto-reconnect method? Thanks.

``` r
# Rscripts
install.packages('RMariaDB')
library(RMariaDB)
con <- dbConnect(RMariaDB::MariaDB(), 
                 user='u367669158_elyry', 
                 password='admin00', 
                 dbname='u367669158_amuvu', 
                 host='sql143.main-hosting.eu')
dbExistsTable(con, "t_demo2")
dbExistsTable(con, "t_demo2")
```
``` r
# console
con <- dbConnect(RMariaDB::MariaDB(), 
+                  user='u367669158_elyry', 
+                  password='admin00', 
+                  dbname='u367669158_amuvu', 
+                  host='sql143.main-hosting.eu')
> dbExistsTable(con, "t_demo2")
[1] TRUE
> dbExistsTable(con, "t_demo2")
[1] FALSE
```

[https://imgur.com/a/Jseegq7](url)

**Comment by krlmlr** [comment]
Thanks. We currently don't try to reconnect to the database if the connection is dead. What does `dbIsValid(con)` return after `dbExistsTable()` is `FALSE` ?

**Comment by smartsurrounding** [comment]
> > dbExistsTable(con, "AA_TRADELOG_700")
> [1] TRUE
> > dbIsValid(con)
> [1] TRUE
> > dbExistsTable(con, "AA_TRADELOG_700")
> [1] FALSE
> > dbIsValid(con)
> [1] TRUE

**Comment by krlmlr** [comment]
No idea what's going on here. Could there be a legitimate reason that the table disappears?

**Comment by krlmlr** [comment]
One way to test if the connection is alive is to issue `dbGetQuery(con, "SELECT 1 AS a")` . This will roundtrip to the database and fail if the connection is dead.

**Comment by smartsurrounding** [comment]
I am 100% sure that the table exists and no reason it disappears... since I usually monitor the db table thru phpMyAdmin panel at the other hand...

**Comment by smartsurrounding** [comment]
Try it again for your reference, thanks!

```R

> dbExistsTable(con, "AA_TRADELOG_700") 
[1] TRUE 
> dbIsValid(con) 
[1] TRUE 
> dbWriteTable(con, "AA_TRADELOG_700", df, append=TRUE, overwrite=FALSE) 



```WAIT FOR 1 MIN


> dbExistsTable(con, "AA_TRADELOG_700") 
[1] FALSE 
> dbIsValid(con) 
[1] TRUE 
> dbGetQuery(con, "SELECT 1 AS a") 
Error in result_create(conn@ptr, statement, is_statement) :  
  MySQL server has gone away [2006]
>

**Comment by krlmlr** [comment]
Thanks. Can you please show the output of `show variables like "%timeout%";` ?

Source: https://stackoverflow.com/a/4284212/946850

See https://www.digitalocean.com/community/questions/how-to-set-no-timeout-to-mysql for configuring these values. I'll try to find a way to detect this condition and reconnect or at least throw an error.

**Comment by bonartm** [comment]
Is there a `timeout` option available when establishing a connection to the db using `DBI::dbConnect(RMariaDB::MariaDB(), ...)`? Right now, R hangs and crashes if I provide a wrong or misspelled db server address. This issue is is similar to https://github.com/r-dbi/odbc/issues/139.

**Comment by bonartm** [comment]
This seems to work:
```R
tmp <- tempfile()
writeLines("[tmp]\nconnect_timeout=3", tmp)
DBI::dbConnect(RMariaDB::MariaDB(), host = "google.com", groups = "tmp", default.file = tmp)
```

**Comment by krlmlr** [comment]
@bonartm: Would you like to contribute a PR with a documentation update?

@smartsurrounding: Closing because information requested was not provided.
